
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Bag
 * 
 */
export type Bag = Prisma.BagModel
/**
 * Model BagPermission
 * 
 */
export type BagPermission = Prisma.BagPermissionModel
/**
 * Model Tiddler
 * 
 */
export type Tiddler = Prisma.TiddlerModel
/**
 * Model TiddlerEvent
 * 
 */
export type TiddlerEvent = Prisma.TiddlerEventModel
/**
 * Model Template
 * 
 */
export type Template = Prisma.TemplateModel
/**
 * Model Recipe
 * 
 */
export type Recipe = Prisma.RecipeModel
/**
 * Model RecipePermission
 * 
 */
export type RecipePermission = Prisma.RecipePermissionModel
/**
 * Model RecipeBag
 * 
 */
export type RecipeBag = Prisma.RecipeBagModel
/**
 * Model Settings
 * 
 */
export type Settings = Prisma.SettingsModel
/**
 * Model Plugin
 * 
 */
export type Plugin = Prisma.PluginModel
/**
 * Model RecipePlugin
 * 
 */
export type RecipePlugin = Prisma.RecipePluginModel
/**
 * Model Roles
 * 
 */
export type Roles = Prisma.RolesModel
/**
 * Model Users
 * 
 */
export type Users = Prisma.UsersModel
/**
 * Model Sessions
 * 
 */
export type Sessions = Prisma.SessionsModel
