
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TiddlerEventType = {
  save: 'save',
  delete: 'delete'
} as const

export type TiddlerEventType = (typeof TiddlerEventType)[keyof typeof TiddlerEventType]


export const BagPermissionLevel = {
  A_read: 'A_read',
  B_write: 'B_write',
  C_admin: 'C_admin'
} as const

export type BagPermissionLevel = (typeof BagPermissionLevel)[keyof typeof BagPermissionLevel]


export const RecipePermissionLevel = {
  A_read: 'A_read',
  B_write: 'B_write'
} as const

export type RecipePermissionLevel = (typeof RecipePermissionLevel)[keyof typeof RecipePermissionLevel]
