
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BagPermission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model BagPermission
 * 
 */
export type BagPermissionModel = runtime.Types.Result.DefaultSelection<Prisma.$BagPermissionPayload>

export type AggregateBagPermission = {
  _count: BagPermissionCountAggregateOutputType | null
  _min: BagPermissionMinAggregateOutputType | null
  _max: BagPermissionMaxAggregateOutputType | null
}

export type BagPermissionMinAggregateOutputType = {
  bag_id: string | null
  role_id: string | null
  level: $Enums.BagPermissionLevel | null
}

export type BagPermissionMaxAggregateOutputType = {
  bag_id: string | null
  role_id: string | null
  level: $Enums.BagPermissionLevel | null
}

export type BagPermissionCountAggregateOutputType = {
  bag_id: number
  role_id: number
  level: number
  _all: number
}


export type BagPermissionMinAggregateInputType = {
  bag_id?: true
  role_id?: true
  level?: true
}

export type BagPermissionMaxAggregateInputType = {
  bag_id?: true
  role_id?: true
  level?: true
}

export type BagPermissionCountAggregateInputType = {
  bag_id?: true
  role_id?: true
  level?: true
  _all?: true
}

export type BagPermissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BagPermission to aggregate.
   */
  where?: Prisma.BagPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BagPermissions to fetch.
   */
  orderBy?: Prisma.BagPermissionOrderByWithRelationInput | Prisma.BagPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BagPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BagPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BagPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BagPermissions
  **/
  _count?: true | BagPermissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BagPermissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BagPermissionMaxAggregateInputType
}

export type GetBagPermissionAggregateType<T extends BagPermissionAggregateArgs> = {
      [P in keyof T & keyof AggregateBagPermission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBagPermission[P]>
    : Prisma.GetScalarType<T[P], AggregateBagPermission[P]>
}




export type BagPermissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BagPermissionWhereInput
  orderBy?: Prisma.BagPermissionOrderByWithAggregationInput | Prisma.BagPermissionOrderByWithAggregationInput[]
  by: Prisma.BagPermissionScalarFieldEnum[] | Prisma.BagPermissionScalarFieldEnum
  having?: Prisma.BagPermissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BagPermissionCountAggregateInputType | true
  _min?: BagPermissionMinAggregateInputType
  _max?: BagPermissionMaxAggregateInputType
}

export type BagPermissionGroupByOutputType = {
  bag_id: string
  role_id: string
  level: $Enums.BagPermissionLevel
  _count: BagPermissionCountAggregateOutputType | null
  _min: BagPermissionMinAggregateOutputType | null
  _max: BagPermissionMaxAggregateOutputType | null
}

type GetBagPermissionGroupByPayload<T extends BagPermissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BagPermissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BagPermissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BagPermissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BagPermissionGroupByOutputType[P]>
      }
    >
  >



export type BagPermissionWhereInput = {
  AND?: Prisma.BagPermissionWhereInput | Prisma.BagPermissionWhereInput[]
  OR?: Prisma.BagPermissionWhereInput[]
  NOT?: Prisma.BagPermissionWhereInput | Prisma.BagPermissionWhereInput[]
  bag_id?: Prisma.StringFilter<"BagPermission"> | string
  role_id?: Prisma.StringFilter<"BagPermission"> | string
  level?: Prisma.EnumBagPermissionLevelFilter<"BagPermission"> | $Enums.BagPermissionLevel
  bag?: Prisma.XOR<Prisma.BagScalarRelationFilter, Prisma.BagWhereInput>
}

export type BagPermissionOrderByWithRelationInput = {
  bag_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  bag?: Prisma.BagOrderByWithRelationInput
}

export type BagPermissionWhereUniqueInput = Prisma.AtLeast<{
  bag_id_role_id?: Prisma.BagPermissionBag_idRole_idCompoundUniqueInput
  AND?: Prisma.BagPermissionWhereInput | Prisma.BagPermissionWhereInput[]
  OR?: Prisma.BagPermissionWhereInput[]
  NOT?: Prisma.BagPermissionWhereInput | Prisma.BagPermissionWhereInput[]
  bag_id?: Prisma.StringFilter<"BagPermission"> | string
  role_id?: Prisma.StringFilter<"BagPermission"> | string
  level?: Prisma.EnumBagPermissionLevelFilter<"BagPermission"> | $Enums.BagPermissionLevel
  bag?: Prisma.XOR<Prisma.BagScalarRelationFilter, Prisma.BagWhereInput>
}, "bag_id_role_id">

export type BagPermissionOrderByWithAggregationInput = {
  bag_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  _count?: Prisma.BagPermissionCountOrderByAggregateInput
  _max?: Prisma.BagPermissionMaxOrderByAggregateInput
  _min?: Prisma.BagPermissionMinOrderByAggregateInput
}

export type BagPermissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.BagPermissionScalarWhereWithAggregatesInput | Prisma.BagPermissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.BagPermissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BagPermissionScalarWhereWithAggregatesInput | Prisma.BagPermissionScalarWhereWithAggregatesInput[]
  bag_id?: Prisma.StringWithAggregatesFilter<"BagPermission"> | string
  role_id?: Prisma.StringWithAggregatesFilter<"BagPermission"> | string
  level?: Prisma.EnumBagPermissionLevelWithAggregatesFilter<"BagPermission"> | $Enums.BagPermissionLevel
}

export type BagPermissionCreateInput = {
  role_id: string
  level: $Enums.BagPermissionLevel
  bag: Prisma.BagCreateNestedOneWithoutPermissionsInput
}

export type BagPermissionUncheckedCreateInput = {
  bag_id: string
  role_id: string
  level: $Enums.BagPermissionLevel
}

export type BagPermissionUpdateInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumBagPermissionLevelFieldUpdateOperationsInput | $Enums.BagPermissionLevel
  bag?: Prisma.BagUpdateOneRequiredWithoutPermissionsNestedInput
}

export type BagPermissionUncheckedUpdateInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumBagPermissionLevelFieldUpdateOperationsInput | $Enums.BagPermissionLevel
}

export type BagPermissionCreateManyInput = {
  bag_id: string
  role_id: string
  level: $Enums.BagPermissionLevel
}

export type BagPermissionUpdateManyMutationInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumBagPermissionLevelFieldUpdateOperationsInput | $Enums.BagPermissionLevel
}

export type BagPermissionUncheckedUpdateManyInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumBagPermissionLevelFieldUpdateOperationsInput | $Enums.BagPermissionLevel
}

export type BagPermissionListRelationFilter = {
  every?: Prisma.BagPermissionWhereInput
  some?: Prisma.BagPermissionWhereInput
  none?: Prisma.BagPermissionWhereInput
}

export type BagPermissionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BagPermissionBag_idRole_idCompoundUniqueInput = {
  bag_id: string
  role_id: string
}

export type BagPermissionCountOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type BagPermissionMaxOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type BagPermissionMinOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type BagPermissionCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.BagPermissionCreateWithoutBagInput, Prisma.BagPermissionUncheckedCreateWithoutBagInput> | Prisma.BagPermissionCreateWithoutBagInput[] | Prisma.BagPermissionUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.BagPermissionCreateOrConnectWithoutBagInput | Prisma.BagPermissionCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.BagPermissionCreateManyBagInputEnvelope
  connect?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
}

export type BagPermissionUncheckedCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.BagPermissionCreateWithoutBagInput, Prisma.BagPermissionUncheckedCreateWithoutBagInput> | Prisma.BagPermissionCreateWithoutBagInput[] | Prisma.BagPermissionUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.BagPermissionCreateOrConnectWithoutBagInput | Prisma.BagPermissionCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.BagPermissionCreateManyBagInputEnvelope
  connect?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
}

export type BagPermissionUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.BagPermissionCreateWithoutBagInput, Prisma.BagPermissionUncheckedCreateWithoutBagInput> | Prisma.BagPermissionCreateWithoutBagInput[] | Prisma.BagPermissionUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.BagPermissionCreateOrConnectWithoutBagInput | Prisma.BagPermissionCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.BagPermissionUpsertWithWhereUniqueWithoutBagInput | Prisma.BagPermissionUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.BagPermissionCreateManyBagInputEnvelope
  set?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  disconnect?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  delete?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  connect?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  update?: Prisma.BagPermissionUpdateWithWhereUniqueWithoutBagInput | Prisma.BagPermissionUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.BagPermissionUpdateManyWithWhereWithoutBagInput | Prisma.BagPermissionUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.BagPermissionScalarWhereInput | Prisma.BagPermissionScalarWhereInput[]
}

export type BagPermissionUncheckedUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.BagPermissionCreateWithoutBagInput, Prisma.BagPermissionUncheckedCreateWithoutBagInput> | Prisma.BagPermissionCreateWithoutBagInput[] | Prisma.BagPermissionUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.BagPermissionCreateOrConnectWithoutBagInput | Prisma.BagPermissionCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.BagPermissionUpsertWithWhereUniqueWithoutBagInput | Prisma.BagPermissionUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.BagPermissionCreateManyBagInputEnvelope
  set?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  disconnect?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  delete?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  connect?: Prisma.BagPermissionWhereUniqueInput | Prisma.BagPermissionWhereUniqueInput[]
  update?: Prisma.BagPermissionUpdateWithWhereUniqueWithoutBagInput | Prisma.BagPermissionUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.BagPermissionUpdateManyWithWhereWithoutBagInput | Prisma.BagPermissionUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.BagPermissionScalarWhereInput | Prisma.BagPermissionScalarWhereInput[]
}

export type EnumBagPermissionLevelFieldUpdateOperationsInput = {
  set?: $Enums.BagPermissionLevel
}

export type BagPermissionCreateWithoutBagInput = {
  role_id: string
  level: $Enums.BagPermissionLevel
}

export type BagPermissionUncheckedCreateWithoutBagInput = {
  role_id: string
  level: $Enums.BagPermissionLevel
}

export type BagPermissionCreateOrConnectWithoutBagInput = {
  where: Prisma.BagPermissionWhereUniqueInput
  create: Prisma.XOR<Prisma.BagPermissionCreateWithoutBagInput, Prisma.BagPermissionUncheckedCreateWithoutBagInput>
}

export type BagPermissionCreateManyBagInputEnvelope = {
  data: Prisma.BagPermissionCreateManyBagInput | Prisma.BagPermissionCreateManyBagInput[]
}

export type BagPermissionUpsertWithWhereUniqueWithoutBagInput = {
  where: Prisma.BagPermissionWhereUniqueInput
  update: Prisma.XOR<Prisma.BagPermissionUpdateWithoutBagInput, Prisma.BagPermissionUncheckedUpdateWithoutBagInput>
  create: Prisma.XOR<Prisma.BagPermissionCreateWithoutBagInput, Prisma.BagPermissionUncheckedCreateWithoutBagInput>
}

export type BagPermissionUpdateWithWhereUniqueWithoutBagInput = {
  where: Prisma.BagPermissionWhereUniqueInput
  data: Prisma.XOR<Prisma.BagPermissionUpdateWithoutBagInput, Prisma.BagPermissionUncheckedUpdateWithoutBagInput>
}

export type BagPermissionUpdateManyWithWhereWithoutBagInput = {
  where: Prisma.BagPermissionScalarWhereInput
  data: Prisma.XOR<Prisma.BagPermissionUpdateManyMutationInput, Prisma.BagPermissionUncheckedUpdateManyWithoutBagInput>
}

export type BagPermissionScalarWhereInput = {
  AND?: Prisma.BagPermissionScalarWhereInput | Prisma.BagPermissionScalarWhereInput[]
  OR?: Prisma.BagPermissionScalarWhereInput[]
  NOT?: Prisma.BagPermissionScalarWhereInput | Prisma.BagPermissionScalarWhereInput[]
  bag_id?: Prisma.StringFilter<"BagPermission"> | string
  role_id?: Prisma.StringFilter<"BagPermission"> | string
  level?: Prisma.EnumBagPermissionLevelFilter<"BagPermission"> | $Enums.BagPermissionLevel
}

export type BagPermissionCreateManyBagInput = {
  role_id: string
  level: $Enums.BagPermissionLevel
}

export type BagPermissionUpdateWithoutBagInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumBagPermissionLevelFieldUpdateOperationsInput | $Enums.BagPermissionLevel
}

export type BagPermissionUncheckedUpdateWithoutBagInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumBagPermissionLevelFieldUpdateOperationsInput | $Enums.BagPermissionLevel
}

export type BagPermissionUncheckedUpdateManyWithoutBagInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumBagPermissionLevelFieldUpdateOperationsInput | $Enums.BagPermissionLevel
}



export type BagPermissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  role_id?: boolean
  level?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bagPermission"]>

export type BagPermissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  role_id?: boolean
  level?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bagPermission"]>

export type BagPermissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  role_id?: boolean
  level?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bagPermission"]>

export type BagPermissionSelectScalar = {
  bag_id?: boolean
  role_id?: boolean
  level?: boolean
}

export type BagPermissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"bag_id" | "role_id" | "level", ExtArgs["result"]["bagPermission"]>
export type BagPermissionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}
export type BagPermissionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}
export type BagPermissionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}

export type $BagPermissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BagPermission"
  objects: {
    bag: Prisma.$BagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    bag_id: string
    role_id: string
    level: $Enums.BagPermissionLevel
  }, ExtArgs["result"]["bagPermission"]>
  composites: {}
}

export type BagPermissionGetPayload<S extends boolean | null | undefined | BagPermissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload, S>

export type BagPermissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BagPermissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BagPermissionCountAggregateInputType | true
  }

export interface BagPermissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BagPermission'], meta: { name: 'BagPermission' } }
  /**
   * Find zero or one BagPermission that matches the filter.
   * @param {BagPermissionFindUniqueArgs} args - Arguments to find a BagPermission
   * @example
   * // Get one BagPermission
   * const bagPermission = await prisma.bagPermission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BagPermissionFindUniqueArgs>(args: Prisma.SelectSubset<T, BagPermissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BagPermission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BagPermissionFindUniqueOrThrowArgs} args - Arguments to find a BagPermission
   * @example
   * // Get one BagPermission
   * const bagPermission = await prisma.bagPermission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BagPermissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BagPermissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BagPermission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagPermissionFindFirstArgs} args - Arguments to find a BagPermission
   * @example
   * // Get one BagPermission
   * const bagPermission = await prisma.bagPermission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BagPermissionFindFirstArgs>(args?: Prisma.SelectSubset<T, BagPermissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BagPermission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagPermissionFindFirstOrThrowArgs} args - Arguments to find a BagPermission
   * @example
   * // Get one BagPermission
   * const bagPermission = await prisma.bagPermission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BagPermissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BagPermissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BagPermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagPermissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BagPermissions
   * const bagPermissions = await prisma.bagPermission.findMany()
   * 
   * // Get first 10 BagPermissions
   * const bagPermissions = await prisma.bagPermission.findMany({ take: 10 })
   * 
   * // Only select the `bag_id`
   * const bagPermissionWithBag_idOnly = await prisma.bagPermission.findMany({ select: { bag_id: true } })
   * 
   */
  findMany<T extends BagPermissionFindManyArgs>(args?: Prisma.SelectSubset<T, BagPermissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BagPermission.
   * @param {BagPermissionCreateArgs} args - Arguments to create a BagPermission.
   * @example
   * // Create one BagPermission
   * const BagPermission = await prisma.bagPermission.create({
   *   data: {
   *     // ... data to create a BagPermission
   *   }
   * })
   * 
   */
  create<T extends BagPermissionCreateArgs>(args: Prisma.SelectSubset<T, BagPermissionCreateArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BagPermissions.
   * @param {BagPermissionCreateManyArgs} args - Arguments to create many BagPermissions.
   * @example
   * // Create many BagPermissions
   * const bagPermission = await prisma.bagPermission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BagPermissionCreateManyArgs>(args?: Prisma.SelectSubset<T, BagPermissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BagPermissions and returns the data saved in the database.
   * @param {BagPermissionCreateManyAndReturnArgs} args - Arguments to create many BagPermissions.
   * @example
   * // Create many BagPermissions
   * const bagPermission = await prisma.bagPermission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BagPermissions and only return the `bag_id`
   * const bagPermissionWithBag_idOnly = await prisma.bagPermission.createManyAndReturn({
   *   select: { bag_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BagPermissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BagPermissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BagPermission.
   * @param {BagPermissionDeleteArgs} args - Arguments to delete one BagPermission.
   * @example
   * // Delete one BagPermission
   * const BagPermission = await prisma.bagPermission.delete({
   *   where: {
   *     // ... filter to delete one BagPermission
   *   }
   * })
   * 
   */
  delete<T extends BagPermissionDeleteArgs>(args: Prisma.SelectSubset<T, BagPermissionDeleteArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BagPermission.
   * @param {BagPermissionUpdateArgs} args - Arguments to update one BagPermission.
   * @example
   * // Update one BagPermission
   * const bagPermission = await prisma.bagPermission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BagPermissionUpdateArgs>(args: Prisma.SelectSubset<T, BagPermissionUpdateArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BagPermissions.
   * @param {BagPermissionDeleteManyArgs} args - Arguments to filter BagPermissions to delete.
   * @example
   * // Delete a few BagPermissions
   * const { count } = await prisma.bagPermission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BagPermissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, BagPermissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BagPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagPermissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BagPermissions
   * const bagPermission = await prisma.bagPermission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BagPermissionUpdateManyArgs>(args: Prisma.SelectSubset<T, BagPermissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BagPermissions and returns the data updated in the database.
   * @param {BagPermissionUpdateManyAndReturnArgs} args - Arguments to update many BagPermissions.
   * @example
   * // Update many BagPermissions
   * const bagPermission = await prisma.bagPermission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BagPermissions and only return the `bag_id`
   * const bagPermissionWithBag_idOnly = await prisma.bagPermission.updateManyAndReturn({
   *   select: { bag_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BagPermissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BagPermissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BagPermission.
   * @param {BagPermissionUpsertArgs} args - Arguments to update or create a BagPermission.
   * @example
   * // Update or create a BagPermission
   * const bagPermission = await prisma.bagPermission.upsert({
   *   create: {
   *     // ... data to create a BagPermission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BagPermission we want to update
   *   }
   * })
   */
  upsert<T extends BagPermissionUpsertArgs>(args: Prisma.SelectSubset<T, BagPermissionUpsertArgs<ExtArgs>>): Prisma.Prisma__BagPermissionClient<runtime.Types.Result.GetResult<Prisma.$BagPermissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BagPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagPermissionCountArgs} args - Arguments to filter BagPermissions to count.
   * @example
   * // Count the number of BagPermissions
   * const count = await prisma.bagPermission.count({
   *   where: {
   *     // ... the filter for the BagPermissions we want to count
   *   }
   * })
  **/
  count<T extends BagPermissionCountArgs>(
    args?: Prisma.Subset<T, BagPermissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BagPermissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BagPermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagPermissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BagPermissionAggregateArgs>(args: Prisma.Subset<T, BagPermissionAggregateArgs>): Prisma.PrismaPromise<GetBagPermissionAggregateType<T>>

  /**
   * Group by BagPermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BagPermissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BagPermissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BagPermissionGroupByArgs['orderBy'] }
      : { orderBy?: BagPermissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BagPermissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBagPermissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BagPermission model
 */
readonly fields: BagPermissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BagPermission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BagPermissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bag<T extends Prisma.BagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BagDefaultArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BagPermission model
 */
export interface BagPermissionFieldRefs {
  readonly bag_id: Prisma.FieldRef<"BagPermission", 'String'>
  readonly role_id: Prisma.FieldRef<"BagPermission", 'String'>
  readonly level: Prisma.FieldRef<"BagPermission", 'BagPermissionLevel'>
}
    

// Custom InputTypes
/**
 * BagPermission findUnique
 */
export type BagPermissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * Filter, which BagPermission to fetch.
   */
  where: Prisma.BagPermissionWhereUniqueInput
}

/**
 * BagPermission findUniqueOrThrow
 */
export type BagPermissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * Filter, which BagPermission to fetch.
   */
  where: Prisma.BagPermissionWhereUniqueInput
}

/**
 * BagPermission findFirst
 */
export type BagPermissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * Filter, which BagPermission to fetch.
   */
  where?: Prisma.BagPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BagPermissions to fetch.
   */
  orderBy?: Prisma.BagPermissionOrderByWithRelationInput | Prisma.BagPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BagPermissions.
   */
  cursor?: Prisma.BagPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BagPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BagPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BagPermissions.
   */
  distinct?: Prisma.BagPermissionScalarFieldEnum | Prisma.BagPermissionScalarFieldEnum[]
}

/**
 * BagPermission findFirstOrThrow
 */
export type BagPermissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * Filter, which BagPermission to fetch.
   */
  where?: Prisma.BagPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BagPermissions to fetch.
   */
  orderBy?: Prisma.BagPermissionOrderByWithRelationInput | Prisma.BagPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BagPermissions.
   */
  cursor?: Prisma.BagPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BagPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BagPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BagPermissions.
   */
  distinct?: Prisma.BagPermissionScalarFieldEnum | Prisma.BagPermissionScalarFieldEnum[]
}

/**
 * BagPermission findMany
 */
export type BagPermissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * Filter, which BagPermissions to fetch.
   */
  where?: Prisma.BagPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BagPermissions to fetch.
   */
  orderBy?: Prisma.BagPermissionOrderByWithRelationInput | Prisma.BagPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BagPermissions.
   */
  cursor?: Prisma.BagPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BagPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BagPermissions.
   */
  skip?: number
  distinct?: Prisma.BagPermissionScalarFieldEnum | Prisma.BagPermissionScalarFieldEnum[]
}

/**
 * BagPermission create
 */
export type BagPermissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * The data needed to create a BagPermission.
   */
  data: Prisma.XOR<Prisma.BagPermissionCreateInput, Prisma.BagPermissionUncheckedCreateInput>
}

/**
 * BagPermission createMany
 */
export type BagPermissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BagPermissions.
   */
  data: Prisma.BagPermissionCreateManyInput | Prisma.BagPermissionCreateManyInput[]
}

/**
 * BagPermission createManyAndReturn
 */
export type BagPermissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * The data used to create many BagPermissions.
   */
  data: Prisma.BagPermissionCreateManyInput | Prisma.BagPermissionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BagPermission update
 */
export type BagPermissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * The data needed to update a BagPermission.
   */
  data: Prisma.XOR<Prisma.BagPermissionUpdateInput, Prisma.BagPermissionUncheckedUpdateInput>
  /**
   * Choose, which BagPermission to update.
   */
  where: Prisma.BagPermissionWhereUniqueInput
}

/**
 * BagPermission updateMany
 */
export type BagPermissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BagPermissions.
   */
  data: Prisma.XOR<Prisma.BagPermissionUpdateManyMutationInput, Prisma.BagPermissionUncheckedUpdateManyInput>
  /**
   * Filter which BagPermissions to update
   */
  where?: Prisma.BagPermissionWhereInput
  /**
   * Limit how many BagPermissions to update.
   */
  limit?: number
}

/**
 * BagPermission updateManyAndReturn
 */
export type BagPermissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * The data used to update BagPermissions.
   */
  data: Prisma.XOR<Prisma.BagPermissionUpdateManyMutationInput, Prisma.BagPermissionUncheckedUpdateManyInput>
  /**
   * Filter which BagPermissions to update
   */
  where?: Prisma.BagPermissionWhereInput
  /**
   * Limit how many BagPermissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BagPermission upsert
 */
export type BagPermissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * The filter to search for the BagPermission to update in case it exists.
   */
  where: Prisma.BagPermissionWhereUniqueInput
  /**
   * In case the BagPermission found by the `where` argument doesn't exist, create a new BagPermission with this data.
   */
  create: Prisma.XOR<Prisma.BagPermissionCreateInput, Prisma.BagPermissionUncheckedCreateInput>
  /**
   * In case the BagPermission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BagPermissionUpdateInput, Prisma.BagPermissionUncheckedUpdateInput>
}

/**
 * BagPermission delete
 */
export type BagPermissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
  /**
   * Filter which BagPermission to delete.
   */
  where: Prisma.BagPermissionWhereUniqueInput
}

/**
 * BagPermission deleteMany
 */
export type BagPermissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BagPermissions to delete
   */
  where?: Prisma.BagPermissionWhereInput
  /**
   * Limit how many BagPermissions to delete.
   */
  limit?: number
}

/**
 * BagPermission without action
 */
export type BagPermissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BagPermission
   */
  select?: Prisma.BagPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BagPermission
   */
  omit?: Prisma.BagPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BagPermissionInclude<ExtArgs> | null
}
