
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Plugin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Plugin
 * 
 */
export type PluginModel = runtime.Types.Result.DefaultSelection<Prisma.$PluginPayload>

export type AggregatePlugin = {
  _count: PluginCountAggregateOutputType | null
  _min: PluginMinAggregateOutputType | null
  _max: PluginMaxAggregateOutputType | null
}

export type PluginMinAggregateOutputType = {
  id: string | null
  name: string | null
  version: string | null
  is_draft: boolean | null
  draft_of: string | null
}

export type PluginMaxAggregateOutputType = {
  id: string | null
  name: string | null
  version: string | null
  is_draft: boolean | null
  draft_of: string | null
}

export type PluginCountAggregateOutputType = {
  id: number
  name: number
  version: number
  is_draft: number
  draft_of: number
  _all: number
}


export type PluginMinAggregateInputType = {
  id?: true
  name?: true
  version?: true
  is_draft?: true
  draft_of?: true
}

export type PluginMaxAggregateInputType = {
  id?: true
  name?: true
  version?: true
  is_draft?: true
  draft_of?: true
}

export type PluginCountAggregateInputType = {
  id?: true
  name?: true
  version?: true
  is_draft?: true
  draft_of?: true
  _all?: true
}

export type PluginAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Plugin to aggregate.
   */
  where?: Prisma.PluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Plugins to fetch.
   */
  orderBy?: Prisma.PluginOrderByWithRelationInput | Prisma.PluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Plugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Plugins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Plugins
  **/
  _count?: true | PluginCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PluginMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PluginMaxAggregateInputType
}

export type GetPluginAggregateType<T extends PluginAggregateArgs> = {
      [P in keyof T & keyof AggregatePlugin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlugin[P]>
    : Prisma.GetScalarType<T[P], AggregatePlugin[P]>
}




export type PluginGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PluginWhereInput
  orderBy?: Prisma.PluginOrderByWithAggregationInput | Prisma.PluginOrderByWithAggregationInput[]
  by: Prisma.PluginScalarFieldEnum[] | Prisma.PluginScalarFieldEnum
  having?: Prisma.PluginScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PluginCountAggregateInputType | true
  _min?: PluginMinAggregateInputType
  _max?: PluginMaxAggregateInputType
}

export type PluginGroupByOutputType = {
  id: string
  name: string
  version: string
  is_draft: boolean
  draft_of: string | null
  _count: PluginCountAggregateOutputType | null
  _min: PluginMinAggregateOutputType | null
  _max: PluginMaxAggregateOutputType | null
}

type GetPluginGroupByPayload<T extends PluginGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PluginGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PluginGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PluginGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PluginGroupByOutputType[P]>
      }
    >
  >



export type PluginWhereInput = {
  AND?: Prisma.PluginWhereInput | Prisma.PluginWhereInput[]
  OR?: Prisma.PluginWhereInput[]
  NOT?: Prisma.PluginWhereInput | Prisma.PluginWhereInput[]
  id?: Prisma.StringFilter<"Plugin"> | string
  name?: Prisma.StringFilter<"Plugin"> | string
  version?: Prisma.StringFilter<"Plugin"> | string
  is_draft?: Prisma.BoolFilter<"Plugin"> | boolean
  draft_of?: Prisma.StringNullableFilter<"Plugin"> | string | null
  recipe_plugins?: Prisma.RecipePluginListRelationFilter
}

export type PluginOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  draft_of?: Prisma.SortOrderInput | Prisma.SortOrder
  recipe_plugins?: Prisma.RecipePluginOrderByRelationAggregateInput
}

export type PluginWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name_version?: Prisma.PluginNameVersionCompoundUniqueInput
  AND?: Prisma.PluginWhereInput | Prisma.PluginWhereInput[]
  OR?: Prisma.PluginWhereInput[]
  NOT?: Prisma.PluginWhereInput | Prisma.PluginWhereInput[]
  name?: Prisma.StringFilter<"Plugin"> | string
  version?: Prisma.StringFilter<"Plugin"> | string
  is_draft?: Prisma.BoolFilter<"Plugin"> | boolean
  draft_of?: Prisma.StringNullableFilter<"Plugin"> | string | null
  recipe_plugins?: Prisma.RecipePluginListRelationFilter
}, "id" | "name_version">

export type PluginOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  draft_of?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PluginCountOrderByAggregateInput
  _max?: Prisma.PluginMaxOrderByAggregateInput
  _min?: Prisma.PluginMinOrderByAggregateInput
}

export type PluginScalarWhereWithAggregatesInput = {
  AND?: Prisma.PluginScalarWhereWithAggregatesInput | Prisma.PluginScalarWhereWithAggregatesInput[]
  OR?: Prisma.PluginScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PluginScalarWhereWithAggregatesInput | Prisma.PluginScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Plugin"> | string
  name?: Prisma.StringWithAggregatesFilter<"Plugin"> | string
  version?: Prisma.StringWithAggregatesFilter<"Plugin"> | string
  is_draft?: Prisma.BoolWithAggregatesFilter<"Plugin"> | boolean
  draft_of?: Prisma.StringNullableWithAggregatesFilter<"Plugin"> | string | null
}

export type PluginCreateInput = {
  id?: string
  name: string
  version: string
  is_draft?: boolean
  draft_of?: string | null
  recipe_plugins?: Prisma.RecipePluginCreateNestedManyWithoutPluginInput
}

export type PluginUncheckedCreateInput = {
  id?: string
  name: string
  version: string
  is_draft?: boolean
  draft_of?: string | null
  recipe_plugins?: Prisma.RecipePluginUncheckedCreateNestedManyWithoutPluginInput
}

export type PluginUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  draft_of?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_plugins?: Prisma.RecipePluginUpdateManyWithoutPluginNestedInput
}

export type PluginUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  draft_of?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipe_plugins?: Prisma.RecipePluginUncheckedUpdateManyWithoutPluginNestedInput
}

export type PluginCreateManyInput = {
  id?: string
  name: string
  version: string
  is_draft?: boolean
  draft_of?: string | null
}

export type PluginUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  draft_of?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PluginUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  draft_of?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PluginNameVersionCompoundUniqueInput = {
  name: string
  version: string
}

export type PluginCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  draft_of?: Prisma.SortOrder
}

export type PluginMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  draft_of?: Prisma.SortOrder
}

export type PluginMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  version?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  draft_of?: Prisma.SortOrder
}

export type PluginScalarRelationFilter = {
  is?: Prisma.PluginWhereInput
  isNot?: Prisma.PluginWhereInput
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type PluginCreateNestedOneWithoutRecipe_pluginsInput = {
  create?: Prisma.XOR<Prisma.PluginCreateWithoutRecipe_pluginsInput, Prisma.PluginUncheckedCreateWithoutRecipe_pluginsInput>
  connectOrCreate?: Prisma.PluginCreateOrConnectWithoutRecipe_pluginsInput
  connect?: Prisma.PluginWhereUniqueInput
}

export type PluginUpdateOneRequiredWithoutRecipe_pluginsNestedInput = {
  create?: Prisma.XOR<Prisma.PluginCreateWithoutRecipe_pluginsInput, Prisma.PluginUncheckedCreateWithoutRecipe_pluginsInput>
  connectOrCreate?: Prisma.PluginCreateOrConnectWithoutRecipe_pluginsInput
  upsert?: Prisma.PluginUpsertWithoutRecipe_pluginsInput
  connect?: Prisma.PluginWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PluginUpdateToOneWithWhereWithoutRecipe_pluginsInput, Prisma.PluginUpdateWithoutRecipe_pluginsInput>, Prisma.PluginUncheckedUpdateWithoutRecipe_pluginsInput>
}

export type PluginCreateWithoutRecipe_pluginsInput = {
  id?: string
  name: string
  version: string
  is_draft?: boolean
  draft_of?: string | null
}

export type PluginUncheckedCreateWithoutRecipe_pluginsInput = {
  id?: string
  name: string
  version: string
  is_draft?: boolean
  draft_of?: string | null
}

export type PluginCreateOrConnectWithoutRecipe_pluginsInput = {
  where: Prisma.PluginWhereUniqueInput
  create: Prisma.XOR<Prisma.PluginCreateWithoutRecipe_pluginsInput, Prisma.PluginUncheckedCreateWithoutRecipe_pluginsInput>
}

export type PluginUpsertWithoutRecipe_pluginsInput = {
  update: Prisma.XOR<Prisma.PluginUpdateWithoutRecipe_pluginsInput, Prisma.PluginUncheckedUpdateWithoutRecipe_pluginsInput>
  create: Prisma.XOR<Prisma.PluginCreateWithoutRecipe_pluginsInput, Prisma.PluginUncheckedCreateWithoutRecipe_pluginsInput>
  where?: Prisma.PluginWhereInput
}

export type PluginUpdateToOneWithWhereWithoutRecipe_pluginsInput = {
  where?: Prisma.PluginWhereInput
  data: Prisma.XOR<Prisma.PluginUpdateWithoutRecipe_pluginsInput, Prisma.PluginUncheckedUpdateWithoutRecipe_pluginsInput>
}

export type PluginUpdateWithoutRecipe_pluginsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  draft_of?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PluginUncheckedUpdateWithoutRecipe_pluginsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.StringFieldUpdateOperationsInput | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  draft_of?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type PluginCountOutputType
 */

export type PluginCountOutputType = {
  recipe_plugins: number
}

export type PluginCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe_plugins?: boolean | PluginCountOutputTypeCountRecipe_pluginsArgs
}

/**
 * PluginCountOutputType without action
 */
export type PluginCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PluginCountOutputType
   */
  select?: Prisma.PluginCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PluginCountOutputType without action
 */
export type PluginCountOutputTypeCountRecipe_pluginsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipePluginWhereInput
}


export type PluginSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  version?: boolean
  is_draft?: boolean
  draft_of?: boolean
  recipe_plugins?: boolean | Prisma.Plugin$recipe_pluginsArgs<ExtArgs>
  _count?: boolean | Prisma.PluginCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["plugin"]>

export type PluginSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  version?: boolean
  is_draft?: boolean
  draft_of?: boolean
}, ExtArgs["result"]["plugin"]>

export type PluginSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  version?: boolean
  is_draft?: boolean
  draft_of?: boolean
}, ExtArgs["result"]["plugin"]>

export type PluginSelectScalar = {
  id?: boolean
  name?: boolean
  version?: boolean
  is_draft?: boolean
  draft_of?: boolean
}

export type PluginOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "version" | "is_draft" | "draft_of", ExtArgs["result"]["plugin"]>
export type PluginInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe_plugins?: boolean | Prisma.Plugin$recipe_pluginsArgs<ExtArgs>
  _count?: boolean | Prisma.PluginCountOutputTypeDefaultArgs<ExtArgs>
}
export type PluginIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PluginIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PluginPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Plugin"
  objects: {
    recipe_plugins: Prisma.$RecipePluginPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    version: string
    is_draft: boolean
    draft_of: string | null
  }, ExtArgs["result"]["plugin"]>
  composites: {}
}

export type PluginGetPayload<S extends boolean | null | undefined | PluginDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PluginPayload, S>

export type PluginCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PluginFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PluginCountAggregateInputType | true
  }

export interface PluginDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Plugin'], meta: { name: 'Plugin' } }
  /**
   * Find zero or one Plugin that matches the filter.
   * @param {PluginFindUniqueArgs} args - Arguments to find a Plugin
   * @example
   * // Get one Plugin
   * const plugin = await prisma.plugin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PluginFindUniqueArgs>(args: Prisma.SelectSubset<T, PluginFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Plugin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PluginFindUniqueOrThrowArgs} args - Arguments to find a Plugin
   * @example
   * // Get one Plugin
   * const plugin = await prisma.plugin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PluginFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PluginFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Plugin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginFindFirstArgs} args - Arguments to find a Plugin
   * @example
   * // Get one Plugin
   * const plugin = await prisma.plugin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PluginFindFirstArgs>(args?: Prisma.SelectSubset<T, PluginFindFirstArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Plugin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginFindFirstOrThrowArgs} args - Arguments to find a Plugin
   * @example
   * // Get one Plugin
   * const plugin = await prisma.plugin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PluginFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PluginFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Plugins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Plugins
   * const plugins = await prisma.plugin.findMany()
   * 
   * // Get first 10 Plugins
   * const plugins = await prisma.plugin.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pluginWithIdOnly = await prisma.plugin.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PluginFindManyArgs>(args?: Prisma.SelectSubset<T, PluginFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Plugin.
   * @param {PluginCreateArgs} args - Arguments to create a Plugin.
   * @example
   * // Create one Plugin
   * const Plugin = await prisma.plugin.create({
   *   data: {
   *     // ... data to create a Plugin
   *   }
   * })
   * 
   */
  create<T extends PluginCreateArgs>(args: Prisma.SelectSubset<T, PluginCreateArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Plugins.
   * @param {PluginCreateManyArgs} args - Arguments to create many Plugins.
   * @example
   * // Create many Plugins
   * const plugin = await prisma.plugin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PluginCreateManyArgs>(args?: Prisma.SelectSubset<T, PluginCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Plugins and returns the data saved in the database.
   * @param {PluginCreateManyAndReturnArgs} args - Arguments to create many Plugins.
   * @example
   * // Create many Plugins
   * const plugin = await prisma.plugin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Plugins and only return the `id`
   * const pluginWithIdOnly = await prisma.plugin.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PluginCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PluginCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Plugin.
   * @param {PluginDeleteArgs} args - Arguments to delete one Plugin.
   * @example
   * // Delete one Plugin
   * const Plugin = await prisma.plugin.delete({
   *   where: {
   *     // ... filter to delete one Plugin
   *   }
   * })
   * 
   */
  delete<T extends PluginDeleteArgs>(args: Prisma.SelectSubset<T, PluginDeleteArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Plugin.
   * @param {PluginUpdateArgs} args - Arguments to update one Plugin.
   * @example
   * // Update one Plugin
   * const plugin = await prisma.plugin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PluginUpdateArgs>(args: Prisma.SelectSubset<T, PluginUpdateArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Plugins.
   * @param {PluginDeleteManyArgs} args - Arguments to filter Plugins to delete.
   * @example
   * // Delete a few Plugins
   * const { count } = await prisma.plugin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PluginDeleteManyArgs>(args?: Prisma.SelectSubset<T, PluginDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Plugins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Plugins
   * const plugin = await prisma.plugin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PluginUpdateManyArgs>(args: Prisma.SelectSubset<T, PluginUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Plugins and returns the data updated in the database.
   * @param {PluginUpdateManyAndReturnArgs} args - Arguments to update many Plugins.
   * @example
   * // Update many Plugins
   * const plugin = await prisma.plugin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Plugins and only return the `id`
   * const pluginWithIdOnly = await prisma.plugin.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PluginUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PluginUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Plugin.
   * @param {PluginUpsertArgs} args - Arguments to update or create a Plugin.
   * @example
   * // Update or create a Plugin
   * const plugin = await prisma.plugin.upsert({
   *   create: {
   *     // ... data to create a Plugin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Plugin we want to update
   *   }
   * })
   */
  upsert<T extends PluginUpsertArgs>(args: Prisma.SelectSubset<T, PluginUpsertArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Plugins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginCountArgs} args - Arguments to filter Plugins to count.
   * @example
   * // Count the number of Plugins
   * const count = await prisma.plugin.count({
   *   where: {
   *     // ... the filter for the Plugins we want to count
   *   }
   * })
  **/
  count<T extends PluginCountArgs>(
    args?: Prisma.Subset<T, PluginCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PluginCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Plugin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PluginAggregateArgs>(args: Prisma.Subset<T, PluginAggregateArgs>): Prisma.PrismaPromise<GetPluginAggregateType<T>>

  /**
   * Group by Plugin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PluginGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PluginGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PluginGroupByArgs['orderBy'] }
      : { orderBy?: PluginGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PluginGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPluginGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Plugin model
 */
readonly fields: PluginFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Plugin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PluginClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe_plugins<T extends Prisma.Plugin$recipe_pluginsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Plugin$recipe_pluginsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Plugin model
 */
export interface PluginFieldRefs {
  readonly id: Prisma.FieldRef<"Plugin", 'String'>
  readonly name: Prisma.FieldRef<"Plugin", 'String'>
  readonly version: Prisma.FieldRef<"Plugin", 'String'>
  readonly is_draft: Prisma.FieldRef<"Plugin", 'Boolean'>
  readonly draft_of: Prisma.FieldRef<"Plugin", 'String'>
}
    

// Custom InputTypes
/**
 * Plugin findUnique
 */
export type PluginFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * Filter, which Plugin to fetch.
   */
  where: Prisma.PluginWhereUniqueInput
}

/**
 * Plugin findUniqueOrThrow
 */
export type PluginFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * Filter, which Plugin to fetch.
   */
  where: Prisma.PluginWhereUniqueInput
}

/**
 * Plugin findFirst
 */
export type PluginFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * Filter, which Plugin to fetch.
   */
  where?: Prisma.PluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Plugins to fetch.
   */
  orderBy?: Prisma.PluginOrderByWithRelationInput | Prisma.PluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Plugins.
   */
  cursor?: Prisma.PluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Plugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Plugins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Plugins.
   */
  distinct?: Prisma.PluginScalarFieldEnum | Prisma.PluginScalarFieldEnum[]
}

/**
 * Plugin findFirstOrThrow
 */
export type PluginFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * Filter, which Plugin to fetch.
   */
  where?: Prisma.PluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Plugins to fetch.
   */
  orderBy?: Prisma.PluginOrderByWithRelationInput | Prisma.PluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Plugins.
   */
  cursor?: Prisma.PluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Plugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Plugins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Plugins.
   */
  distinct?: Prisma.PluginScalarFieldEnum | Prisma.PluginScalarFieldEnum[]
}

/**
 * Plugin findMany
 */
export type PluginFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * Filter, which Plugins to fetch.
   */
  where?: Prisma.PluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Plugins to fetch.
   */
  orderBy?: Prisma.PluginOrderByWithRelationInput | Prisma.PluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Plugins.
   */
  cursor?: Prisma.PluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Plugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Plugins.
   */
  skip?: number
  distinct?: Prisma.PluginScalarFieldEnum | Prisma.PluginScalarFieldEnum[]
}

/**
 * Plugin create
 */
export type PluginCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * The data needed to create a Plugin.
   */
  data: Prisma.XOR<Prisma.PluginCreateInput, Prisma.PluginUncheckedCreateInput>
}

/**
 * Plugin createMany
 */
export type PluginCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Plugins.
   */
  data: Prisma.PluginCreateManyInput | Prisma.PluginCreateManyInput[]
}

/**
 * Plugin createManyAndReturn
 */
export type PluginCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * The data used to create many Plugins.
   */
  data: Prisma.PluginCreateManyInput | Prisma.PluginCreateManyInput[]
}

/**
 * Plugin update
 */
export type PluginUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * The data needed to update a Plugin.
   */
  data: Prisma.XOR<Prisma.PluginUpdateInput, Prisma.PluginUncheckedUpdateInput>
  /**
   * Choose, which Plugin to update.
   */
  where: Prisma.PluginWhereUniqueInput
}

/**
 * Plugin updateMany
 */
export type PluginUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Plugins.
   */
  data: Prisma.XOR<Prisma.PluginUpdateManyMutationInput, Prisma.PluginUncheckedUpdateManyInput>
  /**
   * Filter which Plugins to update
   */
  where?: Prisma.PluginWhereInput
  /**
   * Limit how many Plugins to update.
   */
  limit?: number
}

/**
 * Plugin updateManyAndReturn
 */
export type PluginUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * The data used to update Plugins.
   */
  data: Prisma.XOR<Prisma.PluginUpdateManyMutationInput, Prisma.PluginUncheckedUpdateManyInput>
  /**
   * Filter which Plugins to update
   */
  where?: Prisma.PluginWhereInput
  /**
   * Limit how many Plugins to update.
   */
  limit?: number
}

/**
 * Plugin upsert
 */
export type PluginUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * The filter to search for the Plugin to update in case it exists.
   */
  where: Prisma.PluginWhereUniqueInput
  /**
   * In case the Plugin found by the `where` argument doesn't exist, create a new Plugin with this data.
   */
  create: Prisma.XOR<Prisma.PluginCreateInput, Prisma.PluginUncheckedCreateInput>
  /**
   * In case the Plugin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PluginUpdateInput, Prisma.PluginUncheckedUpdateInput>
}

/**
 * Plugin delete
 */
export type PluginDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
  /**
   * Filter which Plugin to delete.
   */
  where: Prisma.PluginWhereUniqueInput
}

/**
 * Plugin deleteMany
 */
export type PluginDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Plugins to delete
   */
  where?: Prisma.PluginWhereInput
  /**
   * Limit how many Plugins to delete.
   */
  limit?: number
}

/**
 * Plugin.recipe_plugins
 */
export type Plugin$recipe_pluginsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  where?: Prisma.RecipePluginWhereInput
  orderBy?: Prisma.RecipePluginOrderByWithRelationInput | Prisma.RecipePluginOrderByWithRelationInput[]
  cursor?: Prisma.RecipePluginWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecipePluginScalarFieldEnum | Prisma.RecipePluginScalarFieldEnum[]
}

/**
 * Plugin without action
 */
export type PluginDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Plugin
   */
  select?: Prisma.PluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Plugin
   */
  omit?: Prisma.PluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PluginInclude<ExtArgs> | null
}
