
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecipePlugin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model RecipePlugin
 * 
 */
export type RecipePluginModel = runtime.Types.Result.DefaultSelection<Prisma.$RecipePluginPayload>

export type AggregateRecipePlugin = {
  _count: RecipePluginCountAggregateOutputType | null
  _min: RecipePluginMinAggregateOutputType | null
  _max: RecipePluginMaxAggregateOutputType | null
}

export type RecipePluginMinAggregateOutputType = {
  recipe_id: string | null
  plugin_id: string | null
  resolved_version: string | null
}

export type RecipePluginMaxAggregateOutputType = {
  recipe_id: string | null
  plugin_id: string | null
  resolved_version: string | null
}

export type RecipePluginCountAggregateOutputType = {
  recipe_id: number
  plugin_id: number
  resolved_version: number
  _all: number
}


export type RecipePluginMinAggregateInputType = {
  recipe_id?: true
  plugin_id?: true
  resolved_version?: true
}

export type RecipePluginMaxAggregateInputType = {
  recipe_id?: true
  plugin_id?: true
  resolved_version?: true
}

export type RecipePluginCountAggregateInputType = {
  recipe_id?: true
  plugin_id?: true
  resolved_version?: true
  _all?: true
}

export type RecipePluginAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipePlugin to aggregate.
   */
  where?: Prisma.RecipePluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePlugins to fetch.
   */
  orderBy?: Prisma.RecipePluginOrderByWithRelationInput | Prisma.RecipePluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecipePluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePlugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePlugins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecipePlugins
  **/
  _count?: true | RecipePluginCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecipePluginMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecipePluginMaxAggregateInputType
}

export type GetRecipePluginAggregateType<T extends RecipePluginAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipePlugin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipePlugin[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipePlugin[P]>
}




export type RecipePluginGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipePluginWhereInput
  orderBy?: Prisma.RecipePluginOrderByWithAggregationInput | Prisma.RecipePluginOrderByWithAggregationInput[]
  by: Prisma.RecipePluginScalarFieldEnum[] | Prisma.RecipePluginScalarFieldEnum
  having?: Prisma.RecipePluginScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecipePluginCountAggregateInputType | true
  _min?: RecipePluginMinAggregateInputType
  _max?: RecipePluginMaxAggregateInputType
}

export type RecipePluginGroupByOutputType = {
  recipe_id: string
  plugin_id: string
  resolved_version: string
  _count: RecipePluginCountAggregateOutputType | null
  _min: RecipePluginMinAggregateOutputType | null
  _max: RecipePluginMaxAggregateOutputType | null
}

type GetRecipePluginGroupByPayload<T extends RecipePluginGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecipePluginGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecipePluginGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecipePluginGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecipePluginGroupByOutputType[P]>
      }
    >
  >



export type RecipePluginWhereInput = {
  AND?: Prisma.RecipePluginWhereInput | Prisma.RecipePluginWhereInput[]
  OR?: Prisma.RecipePluginWhereInput[]
  NOT?: Prisma.RecipePluginWhereInput | Prisma.RecipePluginWhereInput[]
  recipe_id?: Prisma.StringFilter<"RecipePlugin"> | string
  plugin_id?: Prisma.StringFilter<"RecipePlugin"> | string
  resolved_version?: Prisma.StringFilter<"RecipePlugin"> | string
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
  plugin?: Prisma.XOR<Prisma.PluginScalarRelationFilter, Prisma.PluginWhereInput>
}

export type RecipePluginOrderByWithRelationInput = {
  recipe_id?: Prisma.SortOrder
  plugin_id?: Prisma.SortOrder
  resolved_version?: Prisma.SortOrder
  recipe?: Prisma.RecipeOrderByWithRelationInput
  plugin?: Prisma.PluginOrderByWithRelationInput
}

export type RecipePluginWhereUniqueInput = Prisma.AtLeast<{
  recipe_id_plugin_id?: Prisma.RecipePluginRecipe_idPlugin_idCompoundUniqueInput
  AND?: Prisma.RecipePluginWhereInput | Prisma.RecipePluginWhereInput[]
  OR?: Prisma.RecipePluginWhereInput[]
  NOT?: Prisma.RecipePluginWhereInput | Prisma.RecipePluginWhereInput[]
  recipe_id?: Prisma.StringFilter<"RecipePlugin"> | string
  plugin_id?: Prisma.StringFilter<"RecipePlugin"> | string
  resolved_version?: Prisma.StringFilter<"RecipePlugin"> | string
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
  plugin?: Prisma.XOR<Prisma.PluginScalarRelationFilter, Prisma.PluginWhereInput>
}, "recipe_id_plugin_id">

export type RecipePluginOrderByWithAggregationInput = {
  recipe_id?: Prisma.SortOrder
  plugin_id?: Prisma.SortOrder
  resolved_version?: Prisma.SortOrder
  _count?: Prisma.RecipePluginCountOrderByAggregateInput
  _max?: Prisma.RecipePluginMaxOrderByAggregateInput
  _min?: Prisma.RecipePluginMinOrderByAggregateInput
}

export type RecipePluginScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecipePluginScalarWhereWithAggregatesInput | Prisma.RecipePluginScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecipePluginScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecipePluginScalarWhereWithAggregatesInput | Prisma.RecipePluginScalarWhereWithAggregatesInput[]
  recipe_id?: Prisma.StringWithAggregatesFilter<"RecipePlugin"> | string
  plugin_id?: Prisma.StringWithAggregatesFilter<"RecipePlugin"> | string
  resolved_version?: Prisma.StringWithAggregatesFilter<"RecipePlugin"> | string
}

export type RecipePluginCreateInput = {
  resolved_version: string
  recipe: Prisma.RecipeCreateNestedOneWithoutPluginsInput
  plugin: Prisma.PluginCreateNestedOneWithoutRecipe_pluginsInput
}

export type RecipePluginUncheckedCreateInput = {
  recipe_id: string
  plugin_id: string
  resolved_version: string
}

export type RecipePluginUpdateInput = {
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
  recipe?: Prisma.RecipeUpdateOneRequiredWithoutPluginsNestedInput
  plugin?: Prisma.PluginUpdateOneRequiredWithoutRecipe_pluginsNestedInput
}

export type RecipePluginUncheckedUpdateInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  plugin_id?: Prisma.StringFieldUpdateOperationsInput | string
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipePluginCreateManyInput = {
  recipe_id: string
  plugin_id: string
  resolved_version: string
}

export type RecipePluginUpdateManyMutationInput = {
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipePluginUncheckedUpdateManyInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  plugin_id?: Prisma.StringFieldUpdateOperationsInput | string
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipePluginListRelationFilter = {
  every?: Prisma.RecipePluginWhereInput
  some?: Prisma.RecipePluginWhereInput
  none?: Prisma.RecipePluginWhereInput
}

export type RecipePluginOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecipePluginRecipe_idPlugin_idCompoundUniqueInput = {
  recipe_id: string
  plugin_id: string
}

export type RecipePluginCountOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  plugin_id?: Prisma.SortOrder
  resolved_version?: Prisma.SortOrder
}

export type RecipePluginMaxOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  plugin_id?: Prisma.SortOrder
  resolved_version?: Prisma.SortOrder
}

export type RecipePluginMinOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  plugin_id?: Prisma.SortOrder
  resolved_version?: Prisma.SortOrder
}

export type RecipePluginCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutRecipeInput, Prisma.RecipePluginUncheckedCreateWithoutRecipeInput> | Prisma.RecipePluginCreateWithoutRecipeInput[] | Prisma.RecipePluginUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutRecipeInput | Prisma.RecipePluginCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipePluginCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
}

export type RecipePluginUncheckedCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutRecipeInput, Prisma.RecipePluginUncheckedCreateWithoutRecipeInput> | Prisma.RecipePluginCreateWithoutRecipeInput[] | Prisma.RecipePluginUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutRecipeInput | Prisma.RecipePluginCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipePluginCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
}

export type RecipePluginUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutRecipeInput, Prisma.RecipePluginUncheckedCreateWithoutRecipeInput> | Prisma.RecipePluginCreateWithoutRecipeInput[] | Prisma.RecipePluginUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutRecipeInput | Prisma.RecipePluginCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipePluginUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipePluginUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipePluginCreateManyRecipeInputEnvelope
  set?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  disconnect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  delete?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  update?: Prisma.RecipePluginUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipePluginUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipePluginUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipePluginUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipePluginScalarWhereInput | Prisma.RecipePluginScalarWhereInput[]
}

export type RecipePluginUncheckedUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutRecipeInput, Prisma.RecipePluginUncheckedCreateWithoutRecipeInput> | Prisma.RecipePluginCreateWithoutRecipeInput[] | Prisma.RecipePluginUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutRecipeInput | Prisma.RecipePluginCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipePluginUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipePluginUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipePluginCreateManyRecipeInputEnvelope
  set?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  disconnect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  delete?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  update?: Prisma.RecipePluginUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipePluginUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipePluginUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipePluginUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipePluginScalarWhereInput | Prisma.RecipePluginScalarWhereInput[]
}

export type RecipePluginCreateNestedManyWithoutPluginInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutPluginInput, Prisma.RecipePluginUncheckedCreateWithoutPluginInput> | Prisma.RecipePluginCreateWithoutPluginInput[] | Prisma.RecipePluginUncheckedCreateWithoutPluginInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutPluginInput | Prisma.RecipePluginCreateOrConnectWithoutPluginInput[]
  createMany?: Prisma.RecipePluginCreateManyPluginInputEnvelope
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
}

export type RecipePluginUncheckedCreateNestedManyWithoutPluginInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutPluginInput, Prisma.RecipePluginUncheckedCreateWithoutPluginInput> | Prisma.RecipePluginCreateWithoutPluginInput[] | Prisma.RecipePluginUncheckedCreateWithoutPluginInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutPluginInput | Prisma.RecipePluginCreateOrConnectWithoutPluginInput[]
  createMany?: Prisma.RecipePluginCreateManyPluginInputEnvelope
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
}

export type RecipePluginUpdateManyWithoutPluginNestedInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutPluginInput, Prisma.RecipePluginUncheckedCreateWithoutPluginInput> | Prisma.RecipePluginCreateWithoutPluginInput[] | Prisma.RecipePluginUncheckedCreateWithoutPluginInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutPluginInput | Prisma.RecipePluginCreateOrConnectWithoutPluginInput[]
  upsert?: Prisma.RecipePluginUpsertWithWhereUniqueWithoutPluginInput | Prisma.RecipePluginUpsertWithWhereUniqueWithoutPluginInput[]
  createMany?: Prisma.RecipePluginCreateManyPluginInputEnvelope
  set?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  disconnect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  delete?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  update?: Prisma.RecipePluginUpdateWithWhereUniqueWithoutPluginInput | Prisma.RecipePluginUpdateWithWhereUniqueWithoutPluginInput[]
  updateMany?: Prisma.RecipePluginUpdateManyWithWhereWithoutPluginInput | Prisma.RecipePluginUpdateManyWithWhereWithoutPluginInput[]
  deleteMany?: Prisma.RecipePluginScalarWhereInput | Prisma.RecipePluginScalarWhereInput[]
}

export type RecipePluginUncheckedUpdateManyWithoutPluginNestedInput = {
  create?: Prisma.XOR<Prisma.RecipePluginCreateWithoutPluginInput, Prisma.RecipePluginUncheckedCreateWithoutPluginInput> | Prisma.RecipePluginCreateWithoutPluginInput[] | Prisma.RecipePluginUncheckedCreateWithoutPluginInput[]
  connectOrCreate?: Prisma.RecipePluginCreateOrConnectWithoutPluginInput | Prisma.RecipePluginCreateOrConnectWithoutPluginInput[]
  upsert?: Prisma.RecipePluginUpsertWithWhereUniqueWithoutPluginInput | Prisma.RecipePluginUpsertWithWhereUniqueWithoutPluginInput[]
  createMany?: Prisma.RecipePluginCreateManyPluginInputEnvelope
  set?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  disconnect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  delete?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  connect?: Prisma.RecipePluginWhereUniqueInput | Prisma.RecipePluginWhereUniqueInput[]
  update?: Prisma.RecipePluginUpdateWithWhereUniqueWithoutPluginInput | Prisma.RecipePluginUpdateWithWhereUniqueWithoutPluginInput[]
  updateMany?: Prisma.RecipePluginUpdateManyWithWhereWithoutPluginInput | Prisma.RecipePluginUpdateManyWithWhereWithoutPluginInput[]
  deleteMany?: Prisma.RecipePluginScalarWhereInput | Prisma.RecipePluginScalarWhereInput[]
}

export type RecipePluginCreateWithoutRecipeInput = {
  resolved_version: string
  plugin: Prisma.PluginCreateNestedOneWithoutRecipe_pluginsInput
}

export type RecipePluginUncheckedCreateWithoutRecipeInput = {
  plugin_id: string
  resolved_version: string
}

export type RecipePluginCreateOrConnectWithoutRecipeInput = {
  where: Prisma.RecipePluginWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipePluginCreateWithoutRecipeInput, Prisma.RecipePluginUncheckedCreateWithoutRecipeInput>
}

export type RecipePluginCreateManyRecipeInputEnvelope = {
  data: Prisma.RecipePluginCreateManyRecipeInput | Prisma.RecipePluginCreateManyRecipeInput[]
}

export type RecipePluginUpsertWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipePluginWhereUniqueInput
  update: Prisma.XOR<Prisma.RecipePluginUpdateWithoutRecipeInput, Prisma.RecipePluginUncheckedUpdateWithoutRecipeInput>
  create: Prisma.XOR<Prisma.RecipePluginCreateWithoutRecipeInput, Prisma.RecipePluginUncheckedCreateWithoutRecipeInput>
}

export type RecipePluginUpdateWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipePluginWhereUniqueInput
  data: Prisma.XOR<Prisma.RecipePluginUpdateWithoutRecipeInput, Prisma.RecipePluginUncheckedUpdateWithoutRecipeInput>
}

export type RecipePluginUpdateManyWithWhereWithoutRecipeInput = {
  where: Prisma.RecipePluginScalarWhereInput
  data: Prisma.XOR<Prisma.RecipePluginUpdateManyMutationInput, Prisma.RecipePluginUncheckedUpdateManyWithoutRecipeInput>
}

export type RecipePluginScalarWhereInput = {
  AND?: Prisma.RecipePluginScalarWhereInput | Prisma.RecipePluginScalarWhereInput[]
  OR?: Prisma.RecipePluginScalarWhereInput[]
  NOT?: Prisma.RecipePluginScalarWhereInput | Prisma.RecipePluginScalarWhereInput[]
  recipe_id?: Prisma.StringFilter<"RecipePlugin"> | string
  plugin_id?: Prisma.StringFilter<"RecipePlugin"> | string
  resolved_version?: Prisma.StringFilter<"RecipePlugin"> | string
}

export type RecipePluginCreateWithoutPluginInput = {
  resolved_version: string
  recipe: Prisma.RecipeCreateNestedOneWithoutPluginsInput
}

export type RecipePluginUncheckedCreateWithoutPluginInput = {
  recipe_id: string
  resolved_version: string
}

export type RecipePluginCreateOrConnectWithoutPluginInput = {
  where: Prisma.RecipePluginWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipePluginCreateWithoutPluginInput, Prisma.RecipePluginUncheckedCreateWithoutPluginInput>
}

export type RecipePluginCreateManyPluginInputEnvelope = {
  data: Prisma.RecipePluginCreateManyPluginInput | Prisma.RecipePluginCreateManyPluginInput[]
}

export type RecipePluginUpsertWithWhereUniqueWithoutPluginInput = {
  where: Prisma.RecipePluginWhereUniqueInput
  update: Prisma.XOR<Prisma.RecipePluginUpdateWithoutPluginInput, Prisma.RecipePluginUncheckedUpdateWithoutPluginInput>
  create: Prisma.XOR<Prisma.RecipePluginCreateWithoutPluginInput, Prisma.RecipePluginUncheckedCreateWithoutPluginInput>
}

export type RecipePluginUpdateWithWhereUniqueWithoutPluginInput = {
  where: Prisma.RecipePluginWhereUniqueInput
  data: Prisma.XOR<Prisma.RecipePluginUpdateWithoutPluginInput, Prisma.RecipePluginUncheckedUpdateWithoutPluginInput>
}

export type RecipePluginUpdateManyWithWhereWithoutPluginInput = {
  where: Prisma.RecipePluginScalarWhereInput
  data: Prisma.XOR<Prisma.RecipePluginUpdateManyMutationInput, Prisma.RecipePluginUncheckedUpdateManyWithoutPluginInput>
}

export type RecipePluginCreateManyRecipeInput = {
  plugin_id: string
  resolved_version: string
}

export type RecipePluginUpdateWithoutRecipeInput = {
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
  plugin?: Prisma.PluginUpdateOneRequiredWithoutRecipe_pluginsNestedInput
}

export type RecipePluginUncheckedUpdateWithoutRecipeInput = {
  plugin_id?: Prisma.StringFieldUpdateOperationsInput | string
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipePluginUncheckedUpdateManyWithoutRecipeInput = {
  plugin_id?: Prisma.StringFieldUpdateOperationsInput | string
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipePluginCreateManyPluginInput = {
  recipe_id: string
  resolved_version: string
}

export type RecipePluginUpdateWithoutPluginInput = {
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
  recipe?: Prisma.RecipeUpdateOneRequiredWithoutPluginsNestedInput
}

export type RecipePluginUncheckedUpdateWithoutPluginInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
}

export type RecipePluginUncheckedUpdateManyWithoutPluginInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  resolved_version?: Prisma.StringFieldUpdateOperationsInput | string
}



export type RecipePluginSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  plugin_id?: boolean
  resolved_version?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
  plugin?: boolean | Prisma.PluginDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipePlugin"]>

export type RecipePluginSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  plugin_id?: boolean
  resolved_version?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
  plugin?: boolean | Prisma.PluginDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipePlugin"]>

export type RecipePluginSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  plugin_id?: boolean
  resolved_version?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
  plugin?: boolean | Prisma.PluginDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipePlugin"]>

export type RecipePluginSelectScalar = {
  recipe_id?: boolean
  plugin_id?: boolean
  resolved_version?: boolean
}

export type RecipePluginOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"recipe_id" | "plugin_id" | "resolved_version", ExtArgs["result"]["recipePlugin"]>
export type RecipePluginInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
  plugin?: boolean | Prisma.PluginDefaultArgs<ExtArgs>
}
export type RecipePluginIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
  plugin?: boolean | Prisma.PluginDefaultArgs<ExtArgs>
}
export type RecipePluginIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
  plugin?: boolean | Prisma.PluginDefaultArgs<ExtArgs>
}

export type $RecipePluginPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecipePlugin"
  objects: {
    recipe: Prisma.$RecipePayload<ExtArgs>
    plugin: Prisma.$PluginPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    recipe_id: string
    plugin_id: string
    resolved_version: string
  }, ExtArgs["result"]["recipePlugin"]>
  composites: {}
}

export type RecipePluginGetPayload<S extends boolean | null | undefined | RecipePluginDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload, S>

export type RecipePluginCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecipePluginFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecipePluginCountAggregateInputType | true
  }

export interface RecipePluginDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecipePlugin'], meta: { name: 'RecipePlugin' } }
  /**
   * Find zero or one RecipePlugin that matches the filter.
   * @param {RecipePluginFindUniqueArgs} args - Arguments to find a RecipePlugin
   * @example
   * // Get one RecipePlugin
   * const recipePlugin = await prisma.recipePlugin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecipePluginFindUniqueArgs>(args: Prisma.SelectSubset<T, RecipePluginFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecipePlugin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecipePluginFindUniqueOrThrowArgs} args - Arguments to find a RecipePlugin
   * @example
   * // Get one RecipePlugin
   * const recipePlugin = await prisma.recipePlugin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecipePluginFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecipePluginFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipePlugin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePluginFindFirstArgs} args - Arguments to find a RecipePlugin
   * @example
   * // Get one RecipePlugin
   * const recipePlugin = await prisma.recipePlugin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecipePluginFindFirstArgs>(args?: Prisma.SelectSubset<T, RecipePluginFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipePlugin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePluginFindFirstOrThrowArgs} args - Arguments to find a RecipePlugin
   * @example
   * // Get one RecipePlugin
   * const recipePlugin = await prisma.recipePlugin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecipePluginFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecipePluginFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecipePlugins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePluginFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecipePlugins
   * const recipePlugins = await prisma.recipePlugin.findMany()
   * 
   * // Get first 10 RecipePlugins
   * const recipePlugins = await prisma.recipePlugin.findMany({ take: 10 })
   * 
   * // Only select the `recipe_id`
   * const recipePluginWithRecipe_idOnly = await prisma.recipePlugin.findMany({ select: { recipe_id: true } })
   * 
   */
  findMany<T extends RecipePluginFindManyArgs>(args?: Prisma.SelectSubset<T, RecipePluginFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecipePlugin.
   * @param {RecipePluginCreateArgs} args - Arguments to create a RecipePlugin.
   * @example
   * // Create one RecipePlugin
   * const RecipePlugin = await prisma.recipePlugin.create({
   *   data: {
   *     // ... data to create a RecipePlugin
   *   }
   * })
   * 
   */
  create<T extends RecipePluginCreateArgs>(args: Prisma.SelectSubset<T, RecipePluginCreateArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecipePlugins.
   * @param {RecipePluginCreateManyArgs} args - Arguments to create many RecipePlugins.
   * @example
   * // Create many RecipePlugins
   * const recipePlugin = await prisma.recipePlugin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecipePluginCreateManyArgs>(args?: Prisma.SelectSubset<T, RecipePluginCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecipePlugins and returns the data saved in the database.
   * @param {RecipePluginCreateManyAndReturnArgs} args - Arguments to create many RecipePlugins.
   * @example
   * // Create many RecipePlugins
   * const recipePlugin = await prisma.recipePlugin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecipePlugins and only return the `recipe_id`
   * const recipePluginWithRecipe_idOnly = await prisma.recipePlugin.createManyAndReturn({
   *   select: { recipe_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecipePluginCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecipePluginCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecipePlugin.
   * @param {RecipePluginDeleteArgs} args - Arguments to delete one RecipePlugin.
   * @example
   * // Delete one RecipePlugin
   * const RecipePlugin = await prisma.recipePlugin.delete({
   *   where: {
   *     // ... filter to delete one RecipePlugin
   *   }
   * })
   * 
   */
  delete<T extends RecipePluginDeleteArgs>(args: Prisma.SelectSubset<T, RecipePluginDeleteArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecipePlugin.
   * @param {RecipePluginUpdateArgs} args - Arguments to update one RecipePlugin.
   * @example
   * // Update one RecipePlugin
   * const recipePlugin = await prisma.recipePlugin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecipePluginUpdateArgs>(args: Prisma.SelectSubset<T, RecipePluginUpdateArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecipePlugins.
   * @param {RecipePluginDeleteManyArgs} args - Arguments to filter RecipePlugins to delete.
   * @example
   * // Delete a few RecipePlugins
   * const { count } = await prisma.recipePlugin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecipePluginDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecipePluginDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipePlugins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePluginUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecipePlugins
   * const recipePlugin = await prisma.recipePlugin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecipePluginUpdateManyArgs>(args: Prisma.SelectSubset<T, RecipePluginUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipePlugins and returns the data updated in the database.
   * @param {RecipePluginUpdateManyAndReturnArgs} args - Arguments to update many RecipePlugins.
   * @example
   * // Update many RecipePlugins
   * const recipePlugin = await prisma.recipePlugin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecipePlugins and only return the `recipe_id`
   * const recipePluginWithRecipe_idOnly = await prisma.recipePlugin.updateManyAndReturn({
   *   select: { recipe_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecipePluginUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecipePluginUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecipePlugin.
   * @param {RecipePluginUpsertArgs} args - Arguments to update or create a RecipePlugin.
   * @example
   * // Update or create a RecipePlugin
   * const recipePlugin = await prisma.recipePlugin.upsert({
   *   create: {
   *     // ... data to create a RecipePlugin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecipePlugin we want to update
   *   }
   * })
   */
  upsert<T extends RecipePluginUpsertArgs>(args: Prisma.SelectSubset<T, RecipePluginUpsertArgs<ExtArgs>>): Prisma.Prisma__RecipePluginClient<runtime.Types.Result.GetResult<Prisma.$RecipePluginPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecipePlugins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePluginCountArgs} args - Arguments to filter RecipePlugins to count.
   * @example
   * // Count the number of RecipePlugins
   * const count = await prisma.recipePlugin.count({
   *   where: {
   *     // ... the filter for the RecipePlugins we want to count
   *   }
   * })
  **/
  count<T extends RecipePluginCountArgs>(
    args?: Prisma.Subset<T, RecipePluginCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecipePluginCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecipePlugin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePluginAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecipePluginAggregateArgs>(args: Prisma.Subset<T, RecipePluginAggregateArgs>): Prisma.PrismaPromise<GetRecipePluginAggregateType<T>>

  /**
   * Group by RecipePlugin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePluginGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecipePluginGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecipePluginGroupByArgs['orderBy'] }
      : { orderBy?: RecipePluginGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecipePluginGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipePluginGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecipePlugin model
 */
readonly fields: RecipePluginFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecipePlugin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecipePluginClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe<T extends Prisma.RecipeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RecipeDefaultArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  plugin<T extends Prisma.PluginDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PluginDefaultArgs<ExtArgs>>): Prisma.Prisma__PluginClient<runtime.Types.Result.GetResult<Prisma.$PluginPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecipePlugin model
 */
export interface RecipePluginFieldRefs {
  readonly recipe_id: Prisma.FieldRef<"RecipePlugin", 'String'>
  readonly plugin_id: Prisma.FieldRef<"RecipePlugin", 'String'>
  readonly resolved_version: Prisma.FieldRef<"RecipePlugin", 'String'>
}
    

// Custom InputTypes
/**
 * RecipePlugin findUnique
 */
export type RecipePluginFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * Filter, which RecipePlugin to fetch.
   */
  where: Prisma.RecipePluginWhereUniqueInput
}

/**
 * RecipePlugin findUniqueOrThrow
 */
export type RecipePluginFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * Filter, which RecipePlugin to fetch.
   */
  where: Prisma.RecipePluginWhereUniqueInput
}

/**
 * RecipePlugin findFirst
 */
export type RecipePluginFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * Filter, which RecipePlugin to fetch.
   */
  where?: Prisma.RecipePluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePlugins to fetch.
   */
  orderBy?: Prisma.RecipePluginOrderByWithRelationInput | Prisma.RecipePluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipePlugins.
   */
  cursor?: Prisma.RecipePluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePlugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePlugins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipePlugins.
   */
  distinct?: Prisma.RecipePluginScalarFieldEnum | Prisma.RecipePluginScalarFieldEnum[]
}

/**
 * RecipePlugin findFirstOrThrow
 */
export type RecipePluginFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * Filter, which RecipePlugin to fetch.
   */
  where?: Prisma.RecipePluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePlugins to fetch.
   */
  orderBy?: Prisma.RecipePluginOrderByWithRelationInput | Prisma.RecipePluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipePlugins.
   */
  cursor?: Prisma.RecipePluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePlugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePlugins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipePlugins.
   */
  distinct?: Prisma.RecipePluginScalarFieldEnum | Prisma.RecipePluginScalarFieldEnum[]
}

/**
 * RecipePlugin findMany
 */
export type RecipePluginFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * Filter, which RecipePlugins to fetch.
   */
  where?: Prisma.RecipePluginWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePlugins to fetch.
   */
  orderBy?: Prisma.RecipePluginOrderByWithRelationInput | Prisma.RecipePluginOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecipePlugins.
   */
  cursor?: Prisma.RecipePluginWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePlugins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePlugins.
   */
  skip?: number
  distinct?: Prisma.RecipePluginScalarFieldEnum | Prisma.RecipePluginScalarFieldEnum[]
}

/**
 * RecipePlugin create
 */
export type RecipePluginCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * The data needed to create a RecipePlugin.
   */
  data: Prisma.XOR<Prisma.RecipePluginCreateInput, Prisma.RecipePluginUncheckedCreateInput>
}

/**
 * RecipePlugin createMany
 */
export type RecipePluginCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecipePlugins.
   */
  data: Prisma.RecipePluginCreateManyInput | Prisma.RecipePluginCreateManyInput[]
}

/**
 * RecipePlugin createManyAndReturn
 */
export type RecipePluginCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * The data used to create many RecipePlugins.
   */
  data: Prisma.RecipePluginCreateManyInput | Prisma.RecipePluginCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecipePlugin update
 */
export type RecipePluginUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * The data needed to update a RecipePlugin.
   */
  data: Prisma.XOR<Prisma.RecipePluginUpdateInput, Prisma.RecipePluginUncheckedUpdateInput>
  /**
   * Choose, which RecipePlugin to update.
   */
  where: Prisma.RecipePluginWhereUniqueInput
}

/**
 * RecipePlugin updateMany
 */
export type RecipePluginUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecipePlugins.
   */
  data: Prisma.XOR<Prisma.RecipePluginUpdateManyMutationInput, Prisma.RecipePluginUncheckedUpdateManyInput>
  /**
   * Filter which RecipePlugins to update
   */
  where?: Prisma.RecipePluginWhereInput
  /**
   * Limit how many RecipePlugins to update.
   */
  limit?: number
}

/**
 * RecipePlugin updateManyAndReturn
 */
export type RecipePluginUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * The data used to update RecipePlugins.
   */
  data: Prisma.XOR<Prisma.RecipePluginUpdateManyMutationInput, Prisma.RecipePluginUncheckedUpdateManyInput>
  /**
   * Filter which RecipePlugins to update
   */
  where?: Prisma.RecipePluginWhereInput
  /**
   * Limit how many RecipePlugins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecipePlugin upsert
 */
export type RecipePluginUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * The filter to search for the RecipePlugin to update in case it exists.
   */
  where: Prisma.RecipePluginWhereUniqueInput
  /**
   * In case the RecipePlugin found by the `where` argument doesn't exist, create a new RecipePlugin with this data.
   */
  create: Prisma.XOR<Prisma.RecipePluginCreateInput, Prisma.RecipePluginUncheckedCreateInput>
  /**
   * In case the RecipePlugin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecipePluginUpdateInput, Prisma.RecipePluginUncheckedUpdateInput>
}

/**
 * RecipePlugin delete
 */
export type RecipePluginDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
  /**
   * Filter which RecipePlugin to delete.
   */
  where: Prisma.RecipePluginWhereUniqueInput
}

/**
 * RecipePlugin deleteMany
 */
export type RecipePluginDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipePlugins to delete
   */
  where?: Prisma.RecipePluginWhereInput
  /**
   * Limit how many RecipePlugins to delete.
   */
  limit?: number
}

/**
 * RecipePlugin without action
 */
export type RecipePluginDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePlugin
   */
  select?: Prisma.RecipePluginSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePlugin
   */
  omit?: Prisma.RecipePluginOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePluginInclude<ExtArgs> | null
}
