
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecipePermission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model RecipePermission
 * 
 */
export type RecipePermissionModel = runtime.Types.Result.DefaultSelection<Prisma.$RecipePermissionPayload>

export type AggregateRecipePermission = {
  _count: RecipePermissionCountAggregateOutputType | null
  _min: RecipePermissionMinAggregateOutputType | null
  _max: RecipePermissionMaxAggregateOutputType | null
}

export type RecipePermissionMinAggregateOutputType = {
  recipe_id: string | null
  role_id: string | null
  level: $Enums.RecipePermissionLevel | null
}

export type RecipePermissionMaxAggregateOutputType = {
  recipe_id: string | null
  role_id: string | null
  level: $Enums.RecipePermissionLevel | null
}

export type RecipePermissionCountAggregateOutputType = {
  recipe_id: number
  role_id: number
  level: number
  _all: number
}


export type RecipePermissionMinAggregateInputType = {
  recipe_id?: true
  role_id?: true
  level?: true
}

export type RecipePermissionMaxAggregateInputType = {
  recipe_id?: true
  role_id?: true
  level?: true
}

export type RecipePermissionCountAggregateInputType = {
  recipe_id?: true
  role_id?: true
  level?: true
  _all?: true
}

export type RecipePermissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipePermission to aggregate.
   */
  where?: Prisma.RecipePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePermissions to fetch.
   */
  orderBy?: Prisma.RecipePermissionOrderByWithRelationInput | Prisma.RecipePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecipePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecipePermissions
  **/
  _count?: true | RecipePermissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecipePermissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecipePermissionMaxAggregateInputType
}

export type GetRecipePermissionAggregateType<T extends RecipePermissionAggregateArgs> = {
      [P in keyof T & keyof AggregateRecipePermission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecipePermission[P]>
    : Prisma.GetScalarType<T[P], AggregateRecipePermission[P]>
}




export type RecipePermissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecipePermissionWhereInput
  orderBy?: Prisma.RecipePermissionOrderByWithAggregationInput | Prisma.RecipePermissionOrderByWithAggregationInput[]
  by: Prisma.RecipePermissionScalarFieldEnum[] | Prisma.RecipePermissionScalarFieldEnum
  having?: Prisma.RecipePermissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecipePermissionCountAggregateInputType | true
  _min?: RecipePermissionMinAggregateInputType
  _max?: RecipePermissionMaxAggregateInputType
}

export type RecipePermissionGroupByOutputType = {
  recipe_id: string
  role_id: string
  level: $Enums.RecipePermissionLevel
  _count: RecipePermissionCountAggregateOutputType | null
  _min: RecipePermissionMinAggregateOutputType | null
  _max: RecipePermissionMaxAggregateOutputType | null
}

type GetRecipePermissionGroupByPayload<T extends RecipePermissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecipePermissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecipePermissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecipePermissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecipePermissionGroupByOutputType[P]>
      }
    >
  >



export type RecipePermissionWhereInput = {
  AND?: Prisma.RecipePermissionWhereInput | Prisma.RecipePermissionWhereInput[]
  OR?: Prisma.RecipePermissionWhereInput[]
  NOT?: Prisma.RecipePermissionWhereInput | Prisma.RecipePermissionWhereInput[]
  recipe_id?: Prisma.StringFilter<"RecipePermission"> | string
  role_id?: Prisma.StringFilter<"RecipePermission"> | string
  level?: Prisma.EnumRecipePermissionLevelFilter<"RecipePermission"> | $Enums.RecipePermissionLevel
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
}

export type RecipePermissionOrderByWithRelationInput = {
  recipe_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  recipe?: Prisma.RecipeOrderByWithRelationInput
}

export type RecipePermissionWhereUniqueInput = Prisma.AtLeast<{
  recipe_id_role_id?: Prisma.RecipePermissionRecipe_idRole_idCompoundUniqueInput
  AND?: Prisma.RecipePermissionWhereInput | Prisma.RecipePermissionWhereInput[]
  OR?: Prisma.RecipePermissionWhereInput[]
  NOT?: Prisma.RecipePermissionWhereInput | Prisma.RecipePermissionWhereInput[]
  recipe_id?: Prisma.StringFilter<"RecipePermission"> | string
  role_id?: Prisma.StringFilter<"RecipePermission"> | string
  level?: Prisma.EnumRecipePermissionLevelFilter<"RecipePermission"> | $Enums.RecipePermissionLevel
  recipe?: Prisma.XOR<Prisma.RecipeScalarRelationFilter, Prisma.RecipeWhereInput>
}, "recipe_id_role_id">

export type RecipePermissionOrderByWithAggregationInput = {
  recipe_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  _count?: Prisma.RecipePermissionCountOrderByAggregateInput
  _max?: Prisma.RecipePermissionMaxOrderByAggregateInput
  _min?: Prisma.RecipePermissionMinOrderByAggregateInput
}

export type RecipePermissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecipePermissionScalarWhereWithAggregatesInput | Prisma.RecipePermissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecipePermissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecipePermissionScalarWhereWithAggregatesInput | Prisma.RecipePermissionScalarWhereWithAggregatesInput[]
  recipe_id?: Prisma.StringWithAggregatesFilter<"RecipePermission"> | string
  role_id?: Prisma.StringWithAggregatesFilter<"RecipePermission"> | string
  level?: Prisma.EnumRecipePermissionLevelWithAggregatesFilter<"RecipePermission"> | $Enums.RecipePermissionLevel
}

export type RecipePermissionCreateInput = {
  role_id: string
  level: $Enums.RecipePermissionLevel
  recipe: Prisma.RecipeCreateNestedOneWithoutPermissionsInput
}

export type RecipePermissionUncheckedCreateInput = {
  recipe_id: string
  role_id: string
  level: $Enums.RecipePermissionLevel
}

export type RecipePermissionUpdateInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumRecipePermissionLevelFieldUpdateOperationsInput | $Enums.RecipePermissionLevel
  recipe?: Prisma.RecipeUpdateOneRequiredWithoutPermissionsNestedInput
}

export type RecipePermissionUncheckedUpdateInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumRecipePermissionLevelFieldUpdateOperationsInput | $Enums.RecipePermissionLevel
}

export type RecipePermissionCreateManyInput = {
  recipe_id: string
  role_id: string
  level: $Enums.RecipePermissionLevel
}

export type RecipePermissionUpdateManyMutationInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumRecipePermissionLevelFieldUpdateOperationsInput | $Enums.RecipePermissionLevel
}

export type RecipePermissionUncheckedUpdateManyInput = {
  recipe_id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumRecipePermissionLevelFieldUpdateOperationsInput | $Enums.RecipePermissionLevel
}

export type RecipePermissionListRelationFilter = {
  every?: Prisma.RecipePermissionWhereInput
  some?: Prisma.RecipePermissionWhereInput
  none?: Prisma.RecipePermissionWhereInput
}

export type RecipePermissionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecipePermissionRecipe_idRole_idCompoundUniqueInput = {
  recipe_id: string
  role_id: string
}

export type RecipePermissionCountOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type RecipePermissionMaxOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type RecipePermissionMinOrderByAggregateInput = {
  recipe_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type RecipePermissionCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipePermissionCreateWithoutRecipeInput, Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput> | Prisma.RecipePermissionCreateWithoutRecipeInput[] | Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput | Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipePermissionCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
}

export type RecipePermissionUncheckedCreateNestedManyWithoutRecipeInput = {
  create?: Prisma.XOR<Prisma.RecipePermissionCreateWithoutRecipeInput, Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput> | Prisma.RecipePermissionCreateWithoutRecipeInput[] | Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput | Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput[]
  createMany?: Prisma.RecipePermissionCreateManyRecipeInputEnvelope
  connect?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
}

export type RecipePermissionUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipePermissionCreateWithoutRecipeInput, Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput> | Prisma.RecipePermissionCreateWithoutRecipeInput[] | Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput | Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipePermissionUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipePermissionUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipePermissionCreateManyRecipeInputEnvelope
  set?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  disconnect?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  delete?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  connect?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  update?: Prisma.RecipePermissionUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipePermissionUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipePermissionUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipePermissionUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipePermissionScalarWhereInput | Prisma.RecipePermissionScalarWhereInput[]
}

export type RecipePermissionUncheckedUpdateManyWithoutRecipeNestedInput = {
  create?: Prisma.XOR<Prisma.RecipePermissionCreateWithoutRecipeInput, Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput> | Prisma.RecipePermissionCreateWithoutRecipeInput[] | Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput[]
  connectOrCreate?: Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput | Prisma.RecipePermissionCreateOrConnectWithoutRecipeInput[]
  upsert?: Prisma.RecipePermissionUpsertWithWhereUniqueWithoutRecipeInput | Prisma.RecipePermissionUpsertWithWhereUniqueWithoutRecipeInput[]
  createMany?: Prisma.RecipePermissionCreateManyRecipeInputEnvelope
  set?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  disconnect?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  delete?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  connect?: Prisma.RecipePermissionWhereUniqueInput | Prisma.RecipePermissionWhereUniqueInput[]
  update?: Prisma.RecipePermissionUpdateWithWhereUniqueWithoutRecipeInput | Prisma.RecipePermissionUpdateWithWhereUniqueWithoutRecipeInput[]
  updateMany?: Prisma.RecipePermissionUpdateManyWithWhereWithoutRecipeInput | Prisma.RecipePermissionUpdateManyWithWhereWithoutRecipeInput[]
  deleteMany?: Prisma.RecipePermissionScalarWhereInput | Prisma.RecipePermissionScalarWhereInput[]
}

export type EnumRecipePermissionLevelFieldUpdateOperationsInput = {
  set?: $Enums.RecipePermissionLevel
}

export type RecipePermissionCreateWithoutRecipeInput = {
  role_id: string
  level: $Enums.RecipePermissionLevel
}

export type RecipePermissionUncheckedCreateWithoutRecipeInput = {
  role_id: string
  level: $Enums.RecipePermissionLevel
}

export type RecipePermissionCreateOrConnectWithoutRecipeInput = {
  where: Prisma.RecipePermissionWhereUniqueInput
  create: Prisma.XOR<Prisma.RecipePermissionCreateWithoutRecipeInput, Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput>
}

export type RecipePermissionCreateManyRecipeInputEnvelope = {
  data: Prisma.RecipePermissionCreateManyRecipeInput | Prisma.RecipePermissionCreateManyRecipeInput[]
}

export type RecipePermissionUpsertWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipePermissionWhereUniqueInput
  update: Prisma.XOR<Prisma.RecipePermissionUpdateWithoutRecipeInput, Prisma.RecipePermissionUncheckedUpdateWithoutRecipeInput>
  create: Prisma.XOR<Prisma.RecipePermissionCreateWithoutRecipeInput, Prisma.RecipePermissionUncheckedCreateWithoutRecipeInput>
}

export type RecipePermissionUpdateWithWhereUniqueWithoutRecipeInput = {
  where: Prisma.RecipePermissionWhereUniqueInput
  data: Prisma.XOR<Prisma.RecipePermissionUpdateWithoutRecipeInput, Prisma.RecipePermissionUncheckedUpdateWithoutRecipeInput>
}

export type RecipePermissionUpdateManyWithWhereWithoutRecipeInput = {
  where: Prisma.RecipePermissionScalarWhereInput
  data: Prisma.XOR<Prisma.RecipePermissionUpdateManyMutationInput, Prisma.RecipePermissionUncheckedUpdateManyWithoutRecipeInput>
}

export type RecipePermissionScalarWhereInput = {
  AND?: Prisma.RecipePermissionScalarWhereInput | Prisma.RecipePermissionScalarWhereInput[]
  OR?: Prisma.RecipePermissionScalarWhereInput[]
  NOT?: Prisma.RecipePermissionScalarWhereInput | Prisma.RecipePermissionScalarWhereInput[]
  recipe_id?: Prisma.StringFilter<"RecipePermission"> | string
  role_id?: Prisma.StringFilter<"RecipePermission"> | string
  level?: Prisma.EnumRecipePermissionLevelFilter<"RecipePermission"> | $Enums.RecipePermissionLevel
}

export type RecipePermissionCreateManyRecipeInput = {
  role_id: string
  level: $Enums.RecipePermissionLevel
}

export type RecipePermissionUpdateWithoutRecipeInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumRecipePermissionLevelFieldUpdateOperationsInput | $Enums.RecipePermissionLevel
}

export type RecipePermissionUncheckedUpdateWithoutRecipeInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumRecipePermissionLevelFieldUpdateOperationsInput | $Enums.RecipePermissionLevel
}

export type RecipePermissionUncheckedUpdateManyWithoutRecipeInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumRecipePermissionLevelFieldUpdateOperationsInput | $Enums.RecipePermissionLevel
}



export type RecipePermissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  role_id?: boolean
  level?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipePermission"]>

export type RecipePermissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  role_id?: boolean
  level?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipePermission"]>

export type RecipePermissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recipe_id?: boolean
  role_id?: boolean
  level?: boolean
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recipePermission"]>

export type RecipePermissionSelectScalar = {
  recipe_id?: boolean
  role_id?: boolean
  level?: boolean
}

export type RecipePermissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"recipe_id" | "role_id" | "level", ExtArgs["result"]["recipePermission"]>
export type RecipePermissionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}
export type RecipePermissionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}
export type RecipePermissionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  recipe?: boolean | Prisma.RecipeDefaultArgs<ExtArgs>
}

export type $RecipePermissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecipePermission"
  objects: {
    recipe: Prisma.$RecipePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    recipe_id: string
    role_id: string
    level: $Enums.RecipePermissionLevel
  }, ExtArgs["result"]["recipePermission"]>
  composites: {}
}

export type RecipePermissionGetPayload<S extends boolean | null | undefined | RecipePermissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload, S>

export type RecipePermissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecipePermissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecipePermissionCountAggregateInputType | true
  }

export interface RecipePermissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecipePermission'], meta: { name: 'RecipePermission' } }
  /**
   * Find zero or one RecipePermission that matches the filter.
   * @param {RecipePermissionFindUniqueArgs} args - Arguments to find a RecipePermission
   * @example
   * // Get one RecipePermission
   * const recipePermission = await prisma.recipePermission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecipePermissionFindUniqueArgs>(args: Prisma.SelectSubset<T, RecipePermissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecipePermission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecipePermissionFindUniqueOrThrowArgs} args - Arguments to find a RecipePermission
   * @example
   * // Get one RecipePermission
   * const recipePermission = await prisma.recipePermission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecipePermissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecipePermissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipePermission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePermissionFindFirstArgs} args - Arguments to find a RecipePermission
   * @example
   * // Get one RecipePermission
   * const recipePermission = await prisma.recipePermission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecipePermissionFindFirstArgs>(args?: Prisma.SelectSubset<T, RecipePermissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecipePermission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePermissionFindFirstOrThrowArgs} args - Arguments to find a RecipePermission
   * @example
   * // Get one RecipePermission
   * const recipePermission = await prisma.recipePermission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecipePermissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecipePermissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecipePermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePermissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecipePermissions
   * const recipePermissions = await prisma.recipePermission.findMany()
   * 
   * // Get first 10 RecipePermissions
   * const recipePermissions = await prisma.recipePermission.findMany({ take: 10 })
   * 
   * // Only select the `recipe_id`
   * const recipePermissionWithRecipe_idOnly = await prisma.recipePermission.findMany({ select: { recipe_id: true } })
   * 
   */
  findMany<T extends RecipePermissionFindManyArgs>(args?: Prisma.SelectSubset<T, RecipePermissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecipePermission.
   * @param {RecipePermissionCreateArgs} args - Arguments to create a RecipePermission.
   * @example
   * // Create one RecipePermission
   * const RecipePermission = await prisma.recipePermission.create({
   *   data: {
   *     // ... data to create a RecipePermission
   *   }
   * })
   * 
   */
  create<T extends RecipePermissionCreateArgs>(args: Prisma.SelectSubset<T, RecipePermissionCreateArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecipePermissions.
   * @param {RecipePermissionCreateManyArgs} args - Arguments to create many RecipePermissions.
   * @example
   * // Create many RecipePermissions
   * const recipePermission = await prisma.recipePermission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecipePermissionCreateManyArgs>(args?: Prisma.SelectSubset<T, RecipePermissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecipePermissions and returns the data saved in the database.
   * @param {RecipePermissionCreateManyAndReturnArgs} args - Arguments to create many RecipePermissions.
   * @example
   * // Create many RecipePermissions
   * const recipePermission = await prisma.recipePermission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecipePermissions and only return the `recipe_id`
   * const recipePermissionWithRecipe_idOnly = await prisma.recipePermission.createManyAndReturn({
   *   select: { recipe_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecipePermissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecipePermissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecipePermission.
   * @param {RecipePermissionDeleteArgs} args - Arguments to delete one RecipePermission.
   * @example
   * // Delete one RecipePermission
   * const RecipePermission = await prisma.recipePermission.delete({
   *   where: {
   *     // ... filter to delete one RecipePermission
   *   }
   * })
   * 
   */
  delete<T extends RecipePermissionDeleteArgs>(args: Prisma.SelectSubset<T, RecipePermissionDeleteArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecipePermission.
   * @param {RecipePermissionUpdateArgs} args - Arguments to update one RecipePermission.
   * @example
   * // Update one RecipePermission
   * const recipePermission = await prisma.recipePermission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecipePermissionUpdateArgs>(args: Prisma.SelectSubset<T, RecipePermissionUpdateArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecipePermissions.
   * @param {RecipePermissionDeleteManyArgs} args - Arguments to filter RecipePermissions to delete.
   * @example
   * // Delete a few RecipePermissions
   * const { count } = await prisma.recipePermission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecipePermissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecipePermissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePermissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecipePermissions
   * const recipePermission = await prisma.recipePermission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecipePermissionUpdateManyArgs>(args: Prisma.SelectSubset<T, RecipePermissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecipePermissions and returns the data updated in the database.
   * @param {RecipePermissionUpdateManyAndReturnArgs} args - Arguments to update many RecipePermissions.
   * @example
   * // Update many RecipePermissions
   * const recipePermission = await prisma.recipePermission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecipePermissions and only return the `recipe_id`
   * const recipePermissionWithRecipe_idOnly = await prisma.recipePermission.updateManyAndReturn({
   *   select: { recipe_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecipePermissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecipePermissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecipePermission.
   * @param {RecipePermissionUpsertArgs} args - Arguments to update or create a RecipePermission.
   * @example
   * // Update or create a RecipePermission
   * const recipePermission = await prisma.recipePermission.upsert({
   *   create: {
   *     // ... data to create a RecipePermission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecipePermission we want to update
   *   }
   * })
   */
  upsert<T extends RecipePermissionUpsertArgs>(args: Prisma.SelectSubset<T, RecipePermissionUpsertArgs<ExtArgs>>): Prisma.Prisma__RecipePermissionClient<runtime.Types.Result.GetResult<Prisma.$RecipePermissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecipePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePermissionCountArgs} args - Arguments to filter RecipePermissions to count.
   * @example
   * // Count the number of RecipePermissions
   * const count = await prisma.recipePermission.count({
   *   where: {
   *     // ... the filter for the RecipePermissions we want to count
   *   }
   * })
  **/
  count<T extends RecipePermissionCountArgs>(
    args?: Prisma.Subset<T, RecipePermissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecipePermissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecipePermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePermissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecipePermissionAggregateArgs>(args: Prisma.Subset<T, RecipePermissionAggregateArgs>): Prisma.PrismaPromise<GetRecipePermissionAggregateType<T>>

  /**
   * Group by RecipePermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecipePermissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecipePermissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecipePermissionGroupByArgs['orderBy'] }
      : { orderBy?: RecipePermissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecipePermissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecipePermissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecipePermission model
 */
readonly fields: RecipePermissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecipePermission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecipePermissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  recipe<T extends Prisma.RecipeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RecipeDefaultArgs<ExtArgs>>): Prisma.Prisma__RecipeClient<runtime.Types.Result.GetResult<Prisma.$RecipePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecipePermission model
 */
export interface RecipePermissionFieldRefs {
  readonly recipe_id: Prisma.FieldRef<"RecipePermission", 'String'>
  readonly role_id: Prisma.FieldRef<"RecipePermission", 'String'>
  readonly level: Prisma.FieldRef<"RecipePermission", 'RecipePermissionLevel'>
}
    

// Custom InputTypes
/**
 * RecipePermission findUnique
 */
export type RecipePermissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * Filter, which RecipePermission to fetch.
   */
  where: Prisma.RecipePermissionWhereUniqueInput
}

/**
 * RecipePermission findUniqueOrThrow
 */
export type RecipePermissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * Filter, which RecipePermission to fetch.
   */
  where: Prisma.RecipePermissionWhereUniqueInput
}

/**
 * RecipePermission findFirst
 */
export type RecipePermissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * Filter, which RecipePermission to fetch.
   */
  where?: Prisma.RecipePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePermissions to fetch.
   */
  orderBy?: Prisma.RecipePermissionOrderByWithRelationInput | Prisma.RecipePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipePermissions.
   */
  cursor?: Prisma.RecipePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipePermissions.
   */
  distinct?: Prisma.RecipePermissionScalarFieldEnum | Prisma.RecipePermissionScalarFieldEnum[]
}

/**
 * RecipePermission findFirstOrThrow
 */
export type RecipePermissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * Filter, which RecipePermission to fetch.
   */
  where?: Prisma.RecipePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePermissions to fetch.
   */
  orderBy?: Prisma.RecipePermissionOrderByWithRelationInput | Prisma.RecipePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecipePermissions.
   */
  cursor?: Prisma.RecipePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecipePermissions.
   */
  distinct?: Prisma.RecipePermissionScalarFieldEnum | Prisma.RecipePermissionScalarFieldEnum[]
}

/**
 * RecipePermission findMany
 */
export type RecipePermissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * Filter, which RecipePermissions to fetch.
   */
  where?: Prisma.RecipePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecipePermissions to fetch.
   */
  orderBy?: Prisma.RecipePermissionOrderByWithRelationInput | Prisma.RecipePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecipePermissions.
   */
  cursor?: Prisma.RecipePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecipePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecipePermissions.
   */
  skip?: number
  distinct?: Prisma.RecipePermissionScalarFieldEnum | Prisma.RecipePermissionScalarFieldEnum[]
}

/**
 * RecipePermission create
 */
export type RecipePermissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * The data needed to create a RecipePermission.
   */
  data: Prisma.XOR<Prisma.RecipePermissionCreateInput, Prisma.RecipePermissionUncheckedCreateInput>
}

/**
 * RecipePermission createMany
 */
export type RecipePermissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecipePermissions.
   */
  data: Prisma.RecipePermissionCreateManyInput | Prisma.RecipePermissionCreateManyInput[]
}

/**
 * RecipePermission createManyAndReturn
 */
export type RecipePermissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * The data used to create many RecipePermissions.
   */
  data: Prisma.RecipePermissionCreateManyInput | Prisma.RecipePermissionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecipePermission update
 */
export type RecipePermissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * The data needed to update a RecipePermission.
   */
  data: Prisma.XOR<Prisma.RecipePermissionUpdateInput, Prisma.RecipePermissionUncheckedUpdateInput>
  /**
   * Choose, which RecipePermission to update.
   */
  where: Prisma.RecipePermissionWhereUniqueInput
}

/**
 * RecipePermission updateMany
 */
export type RecipePermissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecipePermissions.
   */
  data: Prisma.XOR<Prisma.RecipePermissionUpdateManyMutationInput, Prisma.RecipePermissionUncheckedUpdateManyInput>
  /**
   * Filter which RecipePermissions to update
   */
  where?: Prisma.RecipePermissionWhereInput
  /**
   * Limit how many RecipePermissions to update.
   */
  limit?: number
}

/**
 * RecipePermission updateManyAndReturn
 */
export type RecipePermissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * The data used to update RecipePermissions.
   */
  data: Prisma.XOR<Prisma.RecipePermissionUpdateManyMutationInput, Prisma.RecipePermissionUncheckedUpdateManyInput>
  /**
   * Filter which RecipePermissions to update
   */
  where?: Prisma.RecipePermissionWhereInput
  /**
   * Limit how many RecipePermissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecipePermission upsert
 */
export type RecipePermissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * The filter to search for the RecipePermission to update in case it exists.
   */
  where: Prisma.RecipePermissionWhereUniqueInput
  /**
   * In case the RecipePermission found by the `where` argument doesn't exist, create a new RecipePermission with this data.
   */
  create: Prisma.XOR<Prisma.RecipePermissionCreateInput, Prisma.RecipePermissionUncheckedCreateInput>
  /**
   * In case the RecipePermission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecipePermissionUpdateInput, Prisma.RecipePermissionUncheckedUpdateInput>
}

/**
 * RecipePermission delete
 */
export type RecipePermissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
  /**
   * Filter which RecipePermission to delete.
   */
  where: Prisma.RecipePermissionWhereUniqueInput
}

/**
 * RecipePermission deleteMany
 */
export type RecipePermissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecipePermissions to delete
   */
  where?: Prisma.RecipePermissionWhereInput
  /**
   * Limit how many RecipePermissions to delete.
   */
  limit?: number
}

/**
 * RecipePermission without action
 */
export type RecipePermissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecipePermission
   */
  select?: Prisma.RecipePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecipePermission
   */
  omit?: Prisma.RecipePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecipePermissionInclude<ExtArgs> | null
}
