
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TemplatePermission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TemplatePermission
 * 
 */
export type TemplatePermissionModel = runtime.Types.Result.DefaultSelection<Prisma.$TemplatePermissionPayload>

export type AggregateTemplatePermission = {
  _count: TemplatePermissionCountAggregateOutputType | null
  _min: TemplatePermissionMinAggregateOutputType | null
  _max: TemplatePermissionMaxAggregateOutputType | null
}

export type TemplatePermissionMinAggregateOutputType = {
  template_id: string | null
  role_id: string | null
  level: $Enums.TemplatePermissionLevel | null
}

export type TemplatePermissionMaxAggregateOutputType = {
  template_id: string | null
  role_id: string | null
  level: $Enums.TemplatePermissionLevel | null
}

export type TemplatePermissionCountAggregateOutputType = {
  template_id: number
  role_id: number
  level: number
  _all: number
}


export type TemplatePermissionMinAggregateInputType = {
  template_id?: true
  role_id?: true
  level?: true
}

export type TemplatePermissionMaxAggregateInputType = {
  template_id?: true
  role_id?: true
  level?: true
}

export type TemplatePermissionCountAggregateInputType = {
  template_id?: true
  role_id?: true
  level?: true
  _all?: true
}

export type TemplatePermissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TemplatePermission to aggregate.
   */
  where?: Prisma.TemplatePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TemplatePermissions to fetch.
   */
  orderBy?: Prisma.TemplatePermissionOrderByWithRelationInput | Prisma.TemplatePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TemplatePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TemplatePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TemplatePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TemplatePermissions
  **/
  _count?: true | TemplatePermissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TemplatePermissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TemplatePermissionMaxAggregateInputType
}

export type GetTemplatePermissionAggregateType<T extends TemplatePermissionAggregateArgs> = {
      [P in keyof T & keyof AggregateTemplatePermission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTemplatePermission[P]>
    : Prisma.GetScalarType<T[P], AggregateTemplatePermission[P]>
}




export type TemplatePermissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TemplatePermissionWhereInput
  orderBy?: Prisma.TemplatePermissionOrderByWithAggregationInput | Prisma.TemplatePermissionOrderByWithAggregationInput[]
  by: Prisma.TemplatePermissionScalarFieldEnum[] | Prisma.TemplatePermissionScalarFieldEnum
  having?: Prisma.TemplatePermissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TemplatePermissionCountAggregateInputType | true
  _min?: TemplatePermissionMinAggregateInputType
  _max?: TemplatePermissionMaxAggregateInputType
}

export type TemplatePermissionGroupByOutputType = {
  template_id: string
  role_id: string
  level: $Enums.TemplatePermissionLevel
  _count: TemplatePermissionCountAggregateOutputType | null
  _min: TemplatePermissionMinAggregateOutputType | null
  _max: TemplatePermissionMaxAggregateOutputType | null
}

export type GetTemplatePermissionGroupByPayload<T extends TemplatePermissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TemplatePermissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TemplatePermissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TemplatePermissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TemplatePermissionGroupByOutputType[P]>
      }
    >
  >



export type TemplatePermissionWhereInput = {
  AND?: Prisma.TemplatePermissionWhereInput | Prisma.TemplatePermissionWhereInput[]
  OR?: Prisma.TemplatePermissionWhereInput[]
  NOT?: Prisma.TemplatePermissionWhereInput | Prisma.TemplatePermissionWhereInput[]
  template_id?: Prisma.StringFilter<"TemplatePermission"> | string
  role_id?: Prisma.StringFilter<"TemplatePermission"> | string
  level?: Prisma.EnumTemplatePermissionLevelFilter<"TemplatePermission"> | $Enums.TemplatePermissionLevel
  template?: Prisma.XOR<Prisma.TemplateScalarRelationFilter, Prisma.TemplateWhereInput>
}

export type TemplatePermissionOrderByWithRelationInput = {
  template_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  template?: Prisma.TemplateOrderByWithRelationInput
}

export type TemplatePermissionWhereUniqueInput = Prisma.AtLeast<{
  template_id_role_id?: Prisma.TemplatePermissionTemplate_idRole_idCompoundUniqueInput
  AND?: Prisma.TemplatePermissionWhereInput | Prisma.TemplatePermissionWhereInput[]
  OR?: Prisma.TemplatePermissionWhereInput[]
  NOT?: Prisma.TemplatePermissionWhereInput | Prisma.TemplatePermissionWhereInput[]
  template_id?: Prisma.StringFilter<"TemplatePermission"> | string
  role_id?: Prisma.StringFilter<"TemplatePermission"> | string
  level?: Prisma.EnumTemplatePermissionLevelFilter<"TemplatePermission"> | $Enums.TemplatePermissionLevel
  template?: Prisma.XOR<Prisma.TemplateScalarRelationFilter, Prisma.TemplateWhereInput>
}, "template_id_role_id">

export type TemplatePermissionOrderByWithAggregationInput = {
  template_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  _count?: Prisma.TemplatePermissionCountOrderByAggregateInput
  _max?: Prisma.TemplatePermissionMaxOrderByAggregateInput
  _min?: Prisma.TemplatePermissionMinOrderByAggregateInput
}

export type TemplatePermissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.TemplatePermissionScalarWhereWithAggregatesInput | Prisma.TemplatePermissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.TemplatePermissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TemplatePermissionScalarWhereWithAggregatesInput | Prisma.TemplatePermissionScalarWhereWithAggregatesInput[]
  template_id?: Prisma.StringWithAggregatesFilter<"TemplatePermission"> | string
  role_id?: Prisma.StringWithAggregatesFilter<"TemplatePermission"> | string
  level?: Prisma.EnumTemplatePermissionLevelWithAggregatesFilter<"TemplatePermission"> | $Enums.TemplatePermissionLevel
}

export type TemplatePermissionCreateInput = {
  role_id: string
  level: $Enums.TemplatePermissionLevel
  template: Prisma.TemplateCreateNestedOneWithoutPermissionsInput
}

export type TemplatePermissionUncheckedCreateInput = {
  template_id: string
  role_id: string
  level: $Enums.TemplatePermissionLevel
}

export type TemplatePermissionUpdateInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumTemplatePermissionLevelFieldUpdateOperationsInput | $Enums.TemplatePermissionLevel
  template?: Prisma.TemplateUpdateOneRequiredWithoutPermissionsNestedInput
}

export type TemplatePermissionUncheckedUpdateInput = {
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumTemplatePermissionLevelFieldUpdateOperationsInput | $Enums.TemplatePermissionLevel
}

export type TemplatePermissionCreateManyInput = {
  template_id: string
  role_id: string
  level: $Enums.TemplatePermissionLevel
}

export type TemplatePermissionUpdateManyMutationInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumTemplatePermissionLevelFieldUpdateOperationsInput | $Enums.TemplatePermissionLevel
}

export type TemplatePermissionUncheckedUpdateManyInput = {
  template_id?: Prisma.StringFieldUpdateOperationsInput | string
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumTemplatePermissionLevelFieldUpdateOperationsInput | $Enums.TemplatePermissionLevel
}

export type TemplatePermissionListRelationFilter = {
  every?: Prisma.TemplatePermissionWhereInput
  some?: Prisma.TemplatePermissionWhereInput
  none?: Prisma.TemplatePermissionWhereInput
}

export type TemplatePermissionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TemplatePermissionTemplate_idRole_idCompoundUniqueInput = {
  template_id: string
  role_id: string
}

export type TemplatePermissionCountOrderByAggregateInput = {
  template_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type TemplatePermissionMaxOrderByAggregateInput = {
  template_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type TemplatePermissionMinOrderByAggregateInput = {
  template_id?: Prisma.SortOrder
  role_id?: Prisma.SortOrder
  level?: Prisma.SortOrder
}

export type TemplatePermissionCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.TemplatePermissionCreateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput> | Prisma.TemplatePermissionCreateWithoutTemplateInput[] | Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput | Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.TemplatePermissionCreateManyTemplateInputEnvelope
  connect?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
}

export type TemplatePermissionUncheckedCreateNestedManyWithoutTemplateInput = {
  create?: Prisma.XOR<Prisma.TemplatePermissionCreateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput> | Prisma.TemplatePermissionCreateWithoutTemplateInput[] | Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput | Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput[]
  createMany?: Prisma.TemplatePermissionCreateManyTemplateInputEnvelope
  connect?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
}

export type TemplatePermissionUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.TemplatePermissionCreateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput> | Prisma.TemplatePermissionCreateWithoutTemplateInput[] | Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput | Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.TemplatePermissionUpsertWithWhereUniqueWithoutTemplateInput | Prisma.TemplatePermissionUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.TemplatePermissionCreateManyTemplateInputEnvelope
  set?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  disconnect?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  delete?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  connect?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  update?: Prisma.TemplatePermissionUpdateWithWhereUniqueWithoutTemplateInput | Prisma.TemplatePermissionUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.TemplatePermissionUpdateManyWithWhereWithoutTemplateInput | Prisma.TemplatePermissionUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.TemplatePermissionScalarWhereInput | Prisma.TemplatePermissionScalarWhereInput[]
}

export type TemplatePermissionUncheckedUpdateManyWithoutTemplateNestedInput = {
  create?: Prisma.XOR<Prisma.TemplatePermissionCreateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput> | Prisma.TemplatePermissionCreateWithoutTemplateInput[] | Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput[]
  connectOrCreate?: Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput | Prisma.TemplatePermissionCreateOrConnectWithoutTemplateInput[]
  upsert?: Prisma.TemplatePermissionUpsertWithWhereUniqueWithoutTemplateInput | Prisma.TemplatePermissionUpsertWithWhereUniqueWithoutTemplateInput[]
  createMany?: Prisma.TemplatePermissionCreateManyTemplateInputEnvelope
  set?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  disconnect?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  delete?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  connect?: Prisma.TemplatePermissionWhereUniqueInput | Prisma.TemplatePermissionWhereUniqueInput[]
  update?: Prisma.TemplatePermissionUpdateWithWhereUniqueWithoutTemplateInput | Prisma.TemplatePermissionUpdateWithWhereUniqueWithoutTemplateInput[]
  updateMany?: Prisma.TemplatePermissionUpdateManyWithWhereWithoutTemplateInput | Prisma.TemplatePermissionUpdateManyWithWhereWithoutTemplateInput[]
  deleteMany?: Prisma.TemplatePermissionScalarWhereInput | Prisma.TemplatePermissionScalarWhereInput[]
}

export type EnumTemplatePermissionLevelFieldUpdateOperationsInput = {
  set?: $Enums.TemplatePermissionLevel
}

export type TemplatePermissionCreateWithoutTemplateInput = {
  role_id: string
  level: $Enums.TemplatePermissionLevel
}

export type TemplatePermissionUncheckedCreateWithoutTemplateInput = {
  role_id: string
  level: $Enums.TemplatePermissionLevel
}

export type TemplatePermissionCreateOrConnectWithoutTemplateInput = {
  where: Prisma.TemplatePermissionWhereUniqueInput
  create: Prisma.XOR<Prisma.TemplatePermissionCreateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput>
}

export type TemplatePermissionCreateManyTemplateInputEnvelope = {
  data: Prisma.TemplatePermissionCreateManyTemplateInput | Prisma.TemplatePermissionCreateManyTemplateInput[]
}

export type TemplatePermissionUpsertWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.TemplatePermissionWhereUniqueInput
  update: Prisma.XOR<Prisma.TemplatePermissionUpdateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedUpdateWithoutTemplateInput>
  create: Prisma.XOR<Prisma.TemplatePermissionCreateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedCreateWithoutTemplateInput>
}

export type TemplatePermissionUpdateWithWhereUniqueWithoutTemplateInput = {
  where: Prisma.TemplatePermissionWhereUniqueInput
  data: Prisma.XOR<Prisma.TemplatePermissionUpdateWithoutTemplateInput, Prisma.TemplatePermissionUncheckedUpdateWithoutTemplateInput>
}

export type TemplatePermissionUpdateManyWithWhereWithoutTemplateInput = {
  where: Prisma.TemplatePermissionScalarWhereInput
  data: Prisma.XOR<Prisma.TemplatePermissionUpdateManyMutationInput, Prisma.TemplatePermissionUncheckedUpdateManyWithoutTemplateInput>
}

export type TemplatePermissionScalarWhereInput = {
  AND?: Prisma.TemplatePermissionScalarWhereInput | Prisma.TemplatePermissionScalarWhereInput[]
  OR?: Prisma.TemplatePermissionScalarWhereInput[]
  NOT?: Prisma.TemplatePermissionScalarWhereInput | Prisma.TemplatePermissionScalarWhereInput[]
  template_id?: Prisma.StringFilter<"TemplatePermission"> | string
  role_id?: Prisma.StringFilter<"TemplatePermission"> | string
  level?: Prisma.EnumTemplatePermissionLevelFilter<"TemplatePermission"> | $Enums.TemplatePermissionLevel
}

export type TemplatePermissionCreateManyTemplateInput = {
  role_id: string
  level: $Enums.TemplatePermissionLevel
}

export type TemplatePermissionUpdateWithoutTemplateInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumTemplatePermissionLevelFieldUpdateOperationsInput | $Enums.TemplatePermissionLevel
}

export type TemplatePermissionUncheckedUpdateWithoutTemplateInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumTemplatePermissionLevelFieldUpdateOperationsInput | $Enums.TemplatePermissionLevel
}

export type TemplatePermissionUncheckedUpdateManyWithoutTemplateInput = {
  role_id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.EnumTemplatePermissionLevelFieldUpdateOperationsInput | $Enums.TemplatePermissionLevel
}



export type TemplatePermissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  template_id?: boolean
  role_id?: boolean
  level?: boolean
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["templatePermission"]>

export type TemplatePermissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  template_id?: boolean
  role_id?: boolean
  level?: boolean
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["templatePermission"]>

export type TemplatePermissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  template_id?: boolean
  role_id?: boolean
  level?: boolean
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}, ExtArgs["result"]["templatePermission"]>

export type TemplatePermissionSelectScalar = {
  template_id?: boolean
  role_id?: boolean
  level?: boolean
}

export type TemplatePermissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"template_id" | "role_id" | "level", ExtArgs["result"]["templatePermission"]>
export type TemplatePermissionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}
export type TemplatePermissionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}
export type TemplatePermissionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  template?: boolean | Prisma.TemplateDefaultArgs<ExtArgs>
}

export type $TemplatePermissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TemplatePermission"
  objects: {
    template: Prisma.$TemplatePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    template_id: string
    role_id: string
    level: $Enums.TemplatePermissionLevel
  }, ExtArgs["result"]["templatePermission"]>
  composites: {}
}

export type TemplatePermissionGetPayload<S extends boolean | null | undefined | TemplatePermissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload, S>

export type TemplatePermissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TemplatePermissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TemplatePermissionCountAggregateInputType | true
  }

export interface TemplatePermissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TemplatePermission'], meta: { name: 'TemplatePermission' } }
  /**
   * Find zero or one TemplatePermission that matches the filter.
   * @param {TemplatePermissionFindUniqueArgs} args - Arguments to find a TemplatePermission
   * @example
   * // Get one TemplatePermission
   * const templatePermission = await prisma.templatePermission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TemplatePermissionFindUniqueArgs>(args: Prisma.SelectSubset<T, TemplatePermissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TemplatePermission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TemplatePermissionFindUniqueOrThrowArgs} args - Arguments to find a TemplatePermission
   * @example
   * // Get one TemplatePermission
   * const templatePermission = await prisma.templatePermission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TemplatePermissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TemplatePermissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TemplatePermission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TemplatePermissionFindFirstArgs} args - Arguments to find a TemplatePermission
   * @example
   * // Get one TemplatePermission
   * const templatePermission = await prisma.templatePermission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TemplatePermissionFindFirstArgs>(args?: Prisma.SelectSubset<T, TemplatePermissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TemplatePermission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TemplatePermissionFindFirstOrThrowArgs} args - Arguments to find a TemplatePermission
   * @example
   * // Get one TemplatePermission
   * const templatePermission = await prisma.templatePermission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TemplatePermissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TemplatePermissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TemplatePermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TemplatePermissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TemplatePermissions
   * const templatePermissions = await prisma.templatePermission.findMany()
   * 
   * // Get first 10 TemplatePermissions
   * const templatePermissions = await prisma.templatePermission.findMany({ take: 10 })
   * 
   * // Only select the `template_id`
   * const templatePermissionWithTemplate_idOnly = await prisma.templatePermission.findMany({ select: { template_id: true } })
   * 
   */
  findMany<T extends TemplatePermissionFindManyArgs>(args?: Prisma.SelectSubset<T, TemplatePermissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TemplatePermission.
   * @param {TemplatePermissionCreateArgs} args - Arguments to create a TemplatePermission.
   * @example
   * // Create one TemplatePermission
   * const TemplatePermission = await prisma.templatePermission.create({
   *   data: {
   *     // ... data to create a TemplatePermission
   *   }
   * })
   * 
   */
  create<T extends TemplatePermissionCreateArgs>(args: Prisma.SelectSubset<T, TemplatePermissionCreateArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TemplatePermissions.
   * @param {TemplatePermissionCreateManyArgs} args - Arguments to create many TemplatePermissions.
   * @example
   * // Create many TemplatePermissions
   * const templatePermission = await prisma.templatePermission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TemplatePermissionCreateManyArgs>(args?: Prisma.SelectSubset<T, TemplatePermissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TemplatePermissions and returns the data saved in the database.
   * @param {TemplatePermissionCreateManyAndReturnArgs} args - Arguments to create many TemplatePermissions.
   * @example
   * // Create many TemplatePermissions
   * const templatePermission = await prisma.templatePermission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TemplatePermissions and only return the `template_id`
   * const templatePermissionWithTemplate_idOnly = await prisma.templatePermission.createManyAndReturn({
   *   select: { template_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TemplatePermissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TemplatePermissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TemplatePermission.
   * @param {TemplatePermissionDeleteArgs} args - Arguments to delete one TemplatePermission.
   * @example
   * // Delete one TemplatePermission
   * const TemplatePermission = await prisma.templatePermission.delete({
   *   where: {
   *     // ... filter to delete one TemplatePermission
   *   }
   * })
   * 
   */
  delete<T extends TemplatePermissionDeleteArgs>(args: Prisma.SelectSubset<T, TemplatePermissionDeleteArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TemplatePermission.
   * @param {TemplatePermissionUpdateArgs} args - Arguments to update one TemplatePermission.
   * @example
   * // Update one TemplatePermission
   * const templatePermission = await prisma.templatePermission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TemplatePermissionUpdateArgs>(args: Prisma.SelectSubset<T, TemplatePermissionUpdateArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TemplatePermissions.
   * @param {TemplatePermissionDeleteManyArgs} args - Arguments to filter TemplatePermissions to delete.
   * @example
   * // Delete a few TemplatePermissions
   * const { count } = await prisma.templatePermission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TemplatePermissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, TemplatePermissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TemplatePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TemplatePermissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TemplatePermissions
   * const templatePermission = await prisma.templatePermission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TemplatePermissionUpdateManyArgs>(args: Prisma.SelectSubset<T, TemplatePermissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TemplatePermissions and returns the data updated in the database.
   * @param {TemplatePermissionUpdateManyAndReturnArgs} args - Arguments to update many TemplatePermissions.
   * @example
   * // Update many TemplatePermissions
   * const templatePermission = await prisma.templatePermission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TemplatePermissions and only return the `template_id`
   * const templatePermissionWithTemplate_idOnly = await prisma.templatePermission.updateManyAndReturn({
   *   select: { template_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TemplatePermissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TemplatePermissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TemplatePermission.
   * @param {TemplatePermissionUpsertArgs} args - Arguments to update or create a TemplatePermission.
   * @example
   * // Update or create a TemplatePermission
   * const templatePermission = await prisma.templatePermission.upsert({
   *   create: {
   *     // ... data to create a TemplatePermission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TemplatePermission we want to update
   *   }
   * })
   */
  upsert<T extends TemplatePermissionUpsertArgs>(args: Prisma.SelectSubset<T, TemplatePermissionUpsertArgs<ExtArgs>>): Prisma.Prisma__TemplatePermissionClient<runtime.Types.Result.GetResult<Prisma.$TemplatePermissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TemplatePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TemplatePermissionCountArgs} args - Arguments to filter TemplatePermissions to count.
   * @example
   * // Count the number of TemplatePermissions
   * const count = await prisma.templatePermission.count({
   *   where: {
   *     // ... the filter for the TemplatePermissions we want to count
   *   }
   * })
  **/
  count<T extends TemplatePermissionCountArgs>(
    args?: Prisma.Subset<T, TemplatePermissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TemplatePermissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TemplatePermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TemplatePermissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TemplatePermissionAggregateArgs>(args: Prisma.Subset<T, TemplatePermissionAggregateArgs>): Prisma.PrismaPromise<GetTemplatePermissionAggregateType<T>>

  /**
   * Group by TemplatePermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TemplatePermissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TemplatePermissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TemplatePermissionGroupByArgs['orderBy'] }
      : { orderBy?: TemplatePermissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TemplatePermissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTemplatePermissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TemplatePermission model
 */
readonly fields: TemplatePermissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TemplatePermission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TemplatePermissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  template<T extends Prisma.TemplateDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TemplateDefaultArgs<ExtArgs>>): Prisma.Prisma__TemplateClient<runtime.Types.Result.GetResult<Prisma.$TemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TemplatePermission model
 */
export interface TemplatePermissionFieldRefs {
  readonly template_id: Prisma.FieldRef<"TemplatePermission", 'String'>
  readonly role_id: Prisma.FieldRef<"TemplatePermission", 'String'>
  readonly level: Prisma.FieldRef<"TemplatePermission", 'TemplatePermissionLevel'>
}
    

// Custom InputTypes
/**
 * TemplatePermission findUnique
 */
export type TemplatePermissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * Filter, which TemplatePermission to fetch.
   */
  where: Prisma.TemplatePermissionWhereUniqueInput
}

/**
 * TemplatePermission findUniqueOrThrow
 */
export type TemplatePermissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * Filter, which TemplatePermission to fetch.
   */
  where: Prisma.TemplatePermissionWhereUniqueInput
}

/**
 * TemplatePermission findFirst
 */
export type TemplatePermissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * Filter, which TemplatePermission to fetch.
   */
  where?: Prisma.TemplatePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TemplatePermissions to fetch.
   */
  orderBy?: Prisma.TemplatePermissionOrderByWithRelationInput | Prisma.TemplatePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TemplatePermissions.
   */
  cursor?: Prisma.TemplatePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TemplatePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TemplatePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TemplatePermissions.
   */
  distinct?: Prisma.TemplatePermissionScalarFieldEnum | Prisma.TemplatePermissionScalarFieldEnum[]
}

/**
 * TemplatePermission findFirstOrThrow
 */
export type TemplatePermissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * Filter, which TemplatePermission to fetch.
   */
  where?: Prisma.TemplatePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TemplatePermissions to fetch.
   */
  orderBy?: Prisma.TemplatePermissionOrderByWithRelationInput | Prisma.TemplatePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TemplatePermissions.
   */
  cursor?: Prisma.TemplatePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TemplatePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TemplatePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TemplatePermissions.
   */
  distinct?: Prisma.TemplatePermissionScalarFieldEnum | Prisma.TemplatePermissionScalarFieldEnum[]
}

/**
 * TemplatePermission findMany
 */
export type TemplatePermissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * Filter, which TemplatePermissions to fetch.
   */
  where?: Prisma.TemplatePermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TemplatePermissions to fetch.
   */
  orderBy?: Prisma.TemplatePermissionOrderByWithRelationInput | Prisma.TemplatePermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TemplatePermissions.
   */
  cursor?: Prisma.TemplatePermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TemplatePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TemplatePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TemplatePermissions.
   */
  distinct?: Prisma.TemplatePermissionScalarFieldEnum | Prisma.TemplatePermissionScalarFieldEnum[]
}

/**
 * TemplatePermission create
 */
export type TemplatePermissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * The data needed to create a TemplatePermission.
   */
  data: Prisma.XOR<Prisma.TemplatePermissionCreateInput, Prisma.TemplatePermissionUncheckedCreateInput>
}

/**
 * TemplatePermission createMany
 */
export type TemplatePermissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TemplatePermissions.
   */
  data: Prisma.TemplatePermissionCreateManyInput | Prisma.TemplatePermissionCreateManyInput[]
}

/**
 * TemplatePermission createManyAndReturn
 */
export type TemplatePermissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * The data used to create many TemplatePermissions.
   */
  data: Prisma.TemplatePermissionCreateManyInput | Prisma.TemplatePermissionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TemplatePermission update
 */
export type TemplatePermissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * The data needed to update a TemplatePermission.
   */
  data: Prisma.XOR<Prisma.TemplatePermissionUpdateInput, Prisma.TemplatePermissionUncheckedUpdateInput>
  /**
   * Choose, which TemplatePermission to update.
   */
  where: Prisma.TemplatePermissionWhereUniqueInput
}

/**
 * TemplatePermission updateMany
 */
export type TemplatePermissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TemplatePermissions.
   */
  data: Prisma.XOR<Prisma.TemplatePermissionUpdateManyMutationInput, Prisma.TemplatePermissionUncheckedUpdateManyInput>
  /**
   * Filter which TemplatePermissions to update
   */
  where?: Prisma.TemplatePermissionWhereInput
  /**
   * Limit how many TemplatePermissions to update.
   */
  limit?: number
}

/**
 * TemplatePermission updateManyAndReturn
 */
export type TemplatePermissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * The data used to update TemplatePermissions.
   */
  data: Prisma.XOR<Prisma.TemplatePermissionUpdateManyMutationInput, Prisma.TemplatePermissionUncheckedUpdateManyInput>
  /**
   * Filter which TemplatePermissions to update
   */
  where?: Prisma.TemplatePermissionWhereInput
  /**
   * Limit how many TemplatePermissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TemplatePermission upsert
 */
export type TemplatePermissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * The filter to search for the TemplatePermission to update in case it exists.
   */
  where: Prisma.TemplatePermissionWhereUniqueInput
  /**
   * In case the TemplatePermission found by the `where` argument doesn't exist, create a new TemplatePermission with this data.
   */
  create: Prisma.XOR<Prisma.TemplatePermissionCreateInput, Prisma.TemplatePermissionUncheckedCreateInput>
  /**
   * In case the TemplatePermission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TemplatePermissionUpdateInput, Prisma.TemplatePermissionUncheckedUpdateInput>
}

/**
 * TemplatePermission delete
 */
export type TemplatePermissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
  /**
   * Filter which TemplatePermission to delete.
   */
  where: Prisma.TemplatePermissionWhereUniqueInput
}

/**
 * TemplatePermission deleteMany
 */
export type TemplatePermissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TemplatePermissions to delete
   */
  where?: Prisma.TemplatePermissionWhereInput
  /**
   * Limit how many TemplatePermissions to delete.
   */
  limit?: number
}

/**
 * TemplatePermission without action
 */
export type TemplatePermissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TemplatePermission
   */
  select?: Prisma.TemplatePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TemplatePermission
   */
  omit?: Prisma.TemplatePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TemplatePermissionInclude<ExtArgs> | null
}
