
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tiddler` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Tiddler
 * 
 */
export type TiddlerModel = runtime.Types.Result.DefaultSelection<Prisma.$TiddlerPayload>

export type AggregateTiddler = {
  _count: TiddlerCountAggregateOutputType | null
  _avg: TiddlerAvgAggregateOutputType | null
  _sum: TiddlerSumAggregateOutputType | null
  _min: TiddlerMinAggregateOutputType | null
  _max: TiddlerMaxAggregateOutputType | null
}

export type TiddlerAvgAggregateOutputType = {
  revision: number | null
}

export type TiddlerSumAggregateOutputType = {
  revision: bigint | null
}

export type TiddlerMinAggregateOutputType = {
  bag_id: string | null
  title: string | null
  created: Date | null
  updated: Date | null
  revision: bigint | null
}

export type TiddlerMaxAggregateOutputType = {
  bag_id: string | null
  title: string | null
  created: Date | null
  updated: Date | null
  revision: bigint | null
}

export type TiddlerCountAggregateOutputType = {
  bag_id: number
  title: number
  created: number
  updated: number
  revision: number
  fields:PrismaJson.Tiddler_fields
  _all: number
}


export type TiddlerAvgAggregateInputType = {
  revision?: true
}

export type TiddlerSumAggregateInputType = {
  revision?: true
}

export type TiddlerMinAggregateInputType = {
  bag_id?: true
  title?: true
  created?: true
  updated?: true
  revision?: true
}

export type TiddlerMaxAggregateInputType = {
  bag_id?: true
  title?: true
  created?: true
  updated?: true
  revision?: true
}

export type TiddlerCountAggregateInputType = {
  bag_id?: true
  title?: true
  created?: true
  updated?: true
  revision?: true
  fields?: true
  _all?: true
}

export type TiddlerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tiddler to aggregate.
   */
  where?: Prisma.TiddlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlerOrderByWithRelationInput | Prisma.TiddlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TiddlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tiddlers
  **/
  _count?: true | TiddlerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TiddlerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TiddlerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TiddlerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TiddlerMaxAggregateInputType
}

export type GetTiddlerAggregateType<T extends TiddlerAggregateArgs> = {
      [P in keyof T & keyof AggregateTiddler]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTiddler[P]>
    : Prisma.GetScalarType<T[P], AggregateTiddler[P]>
}




export type TiddlerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TiddlerWhereInput
  orderBy?: Prisma.TiddlerOrderByWithAggregationInput | Prisma.TiddlerOrderByWithAggregationInput[]
  by: Prisma.TiddlerScalarFieldEnum[] | Prisma.TiddlerScalarFieldEnum
  having?: Prisma.TiddlerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TiddlerCountAggregateInputType | true
  _avg?: TiddlerAvgAggregateInputType
  _sum?: TiddlerSumAggregateInputType
  _min?: TiddlerMinAggregateInputType
  _max?: TiddlerMaxAggregateInputType
}

export type TiddlerGroupByOutputType = {
  bag_id: string
  title: string
  created: Date
  updated: Date
  revision: bigint
  fields:PrismaJson.Tiddler_fields
  _count: TiddlerCountAggregateOutputType | null
  _avg: TiddlerAvgAggregateOutputType | null
  _sum: TiddlerSumAggregateOutputType | null
  _min: TiddlerMinAggregateOutputType | null
  _max: TiddlerMaxAggregateOutputType | null
}

type GetTiddlerGroupByPayload<T extends TiddlerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TiddlerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TiddlerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TiddlerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TiddlerGroupByOutputType[P]>
      }
    >
  >



export type TiddlerWhereInput = {
  AND?: Prisma.TiddlerWhereInput | Prisma.TiddlerWhereInput[]
  OR?: Prisma.TiddlerWhereInput[]
  NOT?: Prisma.TiddlerWhereInput | Prisma.TiddlerWhereInput[]
  bag_id?: Prisma.StringFilter<"Tiddler"> | string
  title?: Prisma.StringFilter<"Tiddler"> | string
  created?: Prisma.DateTimeFilter<"Tiddler"> | Date | string
  updated?: Prisma.DateTimeFilter<"Tiddler"> | Date | string
  revision?: Prisma.BigIntFilter<"Tiddler"> | bigint | number
  fields?: Prisma.JsonFilter<"Tiddler">
  bag?: Prisma.XOR<Prisma.BagScalarRelationFilter, Prisma.BagWhereInput>
}

export type TiddlerOrderByWithRelationInput = {
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  revision?: Prisma.SortOrder
  fields?: Prisma.SortOrder
  bag?: Prisma.BagOrderByWithRelationInput
}

export type TiddlerWhereUniqueInput = Prisma.AtLeast<{
  bag_id_title?: Prisma.TiddlerBag_idTitleCompoundUniqueInput
  AND?: Prisma.TiddlerWhereInput | Prisma.TiddlerWhereInput[]
  OR?: Prisma.TiddlerWhereInput[]
  NOT?: Prisma.TiddlerWhereInput | Prisma.TiddlerWhereInput[]
  bag_id?: Prisma.StringFilter<"Tiddler"> | string
  title?: Prisma.StringFilter<"Tiddler"> | string
  created?: Prisma.DateTimeFilter<"Tiddler"> | Date | string
  updated?: Prisma.DateTimeFilter<"Tiddler"> | Date | string
  revision?: Prisma.BigIntFilter<"Tiddler"> | bigint | number
  fields?: Prisma.JsonFilter<"Tiddler">
  bag?: Prisma.XOR<Prisma.BagScalarRelationFilter, Prisma.BagWhereInput>
}, "bag_id_title">

export type TiddlerOrderByWithAggregationInput = {
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  revision?: Prisma.SortOrder
  fields?: Prisma.SortOrder
  _count?: Prisma.TiddlerCountOrderByAggregateInput
  _avg?: Prisma.TiddlerAvgOrderByAggregateInput
  _max?: Prisma.TiddlerMaxOrderByAggregateInput
  _min?: Prisma.TiddlerMinOrderByAggregateInput
  _sum?: Prisma.TiddlerSumOrderByAggregateInput
}

export type TiddlerScalarWhereWithAggregatesInput = {
  AND?: Prisma.TiddlerScalarWhereWithAggregatesInput | Prisma.TiddlerScalarWhereWithAggregatesInput[]
  OR?: Prisma.TiddlerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TiddlerScalarWhereWithAggregatesInput | Prisma.TiddlerScalarWhereWithAggregatesInput[]
  bag_id?: Prisma.StringWithAggregatesFilter<"Tiddler"> | string
  title?: Prisma.StringWithAggregatesFilter<"Tiddler"> | string
  created?: Prisma.DateTimeWithAggregatesFilter<"Tiddler"> | Date | string
  updated?: Prisma.DateTimeWithAggregatesFilter<"Tiddler"> | Date | string
  revision?: Prisma.BigIntWithAggregatesFilter<"Tiddler"> | bigint | number
  fields?: Prisma.JsonWithAggregatesFilter<"Tiddler">
}

export type TiddlerCreateInput = {
  title: string
  created?: Date | string
  updated?: Date | string
  revision?: bigint | number
  fields:PrismaJson.Tiddler_fields
  bag: Prisma.BagCreateNestedOneWithoutTiddlersInput
}

export type TiddlerUncheckedCreateInput = {
  bag_id: string
  title: string
  created?: Date | string
  updated?: Date | string
  revision?: bigint | number
  fields:PrismaJson.Tiddler_fields
}

export type TiddlerUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revision?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fields?:PrismaJson.Tiddler_fields
  bag?: Prisma.BagUpdateOneRequiredWithoutTiddlersNestedInput
}

export type TiddlerUncheckedUpdateInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revision?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fields?:PrismaJson.Tiddler_fields
}

export type TiddlerCreateManyInput = {
  bag_id: string
  title: string
  created?: Date | string
  updated?: Date | string
  revision?: bigint | number
  fields:PrismaJson.Tiddler_fields
}

export type TiddlerUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revision?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fields?:PrismaJson.Tiddler_fields
}

export type TiddlerUncheckedUpdateManyInput = {
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revision?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fields?:PrismaJson.Tiddler_fields
}

export type TiddlerListRelationFilter = {
  every?: Prisma.TiddlerWhereInput
  some?: Prisma.TiddlerWhereInput
  none?: Prisma.TiddlerWhereInput
}

export type TiddlerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TiddlerBag_idTitleCompoundUniqueInput = {
  bag_id: string
  title: string
}

export type TiddlerCountOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  revision?: Prisma.SortOrder
  fields?: Prisma.SortOrder
}

export type TiddlerAvgOrderByAggregateInput = {
  revision?: Prisma.SortOrder
}

export type TiddlerMaxOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  revision?: Prisma.SortOrder
}

export type TiddlerMinOrderByAggregateInput = {
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  created?: Prisma.SortOrder
  updated?: Prisma.SortOrder
  revision?: Prisma.SortOrder
}

export type TiddlerSumOrderByAggregateInput = {
  revision?: Prisma.SortOrder
}

export type TiddlerCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.TiddlerCreateWithoutBagInput, Prisma.TiddlerUncheckedCreateWithoutBagInput> | Prisma.TiddlerCreateWithoutBagInput[] | Prisma.TiddlerUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerCreateOrConnectWithoutBagInput | Prisma.TiddlerCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.TiddlerCreateManyBagInputEnvelope
  connect?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
}

export type TiddlerUncheckedCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.TiddlerCreateWithoutBagInput, Prisma.TiddlerUncheckedCreateWithoutBagInput> | Prisma.TiddlerCreateWithoutBagInput[] | Prisma.TiddlerUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerCreateOrConnectWithoutBagInput | Prisma.TiddlerCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.TiddlerCreateManyBagInputEnvelope
  connect?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
}

export type TiddlerUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.TiddlerCreateWithoutBagInput, Prisma.TiddlerUncheckedCreateWithoutBagInput> | Prisma.TiddlerCreateWithoutBagInput[] | Prisma.TiddlerUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerCreateOrConnectWithoutBagInput | Prisma.TiddlerCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.TiddlerUpsertWithWhereUniqueWithoutBagInput | Prisma.TiddlerUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.TiddlerCreateManyBagInputEnvelope
  set?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  disconnect?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  delete?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  connect?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  update?: Prisma.TiddlerUpdateWithWhereUniqueWithoutBagInput | Prisma.TiddlerUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.TiddlerUpdateManyWithWhereWithoutBagInput | Prisma.TiddlerUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.TiddlerScalarWhereInput | Prisma.TiddlerScalarWhereInput[]
}

export type TiddlerUncheckedUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.TiddlerCreateWithoutBagInput, Prisma.TiddlerUncheckedCreateWithoutBagInput> | Prisma.TiddlerCreateWithoutBagInput[] | Prisma.TiddlerUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerCreateOrConnectWithoutBagInput | Prisma.TiddlerCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.TiddlerUpsertWithWhereUniqueWithoutBagInput | Prisma.TiddlerUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.TiddlerCreateManyBagInputEnvelope
  set?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  disconnect?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  delete?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  connect?: Prisma.TiddlerWhereUniqueInput | Prisma.TiddlerWhereUniqueInput[]
  update?: Prisma.TiddlerUpdateWithWhereUniqueWithoutBagInput | Prisma.TiddlerUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.TiddlerUpdateManyWithWhereWithoutBagInput | Prisma.TiddlerUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.TiddlerScalarWhereInput | Prisma.TiddlerScalarWhereInput[]
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type TiddlerCreateWithoutBagInput = {
  title: string
  created?: Date | string
  updated?: Date | string
  revision?: bigint | number
  fields:PrismaJson.Tiddler_fields
}

export type TiddlerUncheckedCreateWithoutBagInput = {
  title: string
  created?: Date | string
  updated?: Date | string
  revision?: bigint | number
  fields:PrismaJson.Tiddler_fields
}

export type TiddlerCreateOrConnectWithoutBagInput = {
  where: Prisma.TiddlerWhereUniqueInput
  create: Prisma.XOR<Prisma.TiddlerCreateWithoutBagInput, Prisma.TiddlerUncheckedCreateWithoutBagInput>
}

export type TiddlerCreateManyBagInputEnvelope = {
  data: Prisma.TiddlerCreateManyBagInput | Prisma.TiddlerCreateManyBagInput[]
}

export type TiddlerUpsertWithWhereUniqueWithoutBagInput = {
  where: Prisma.TiddlerWhereUniqueInput
  update: Prisma.XOR<Prisma.TiddlerUpdateWithoutBagInput, Prisma.TiddlerUncheckedUpdateWithoutBagInput>
  create: Prisma.XOR<Prisma.TiddlerCreateWithoutBagInput, Prisma.TiddlerUncheckedCreateWithoutBagInput>
}

export type TiddlerUpdateWithWhereUniqueWithoutBagInput = {
  where: Prisma.TiddlerWhereUniqueInput
  data: Prisma.XOR<Prisma.TiddlerUpdateWithoutBagInput, Prisma.TiddlerUncheckedUpdateWithoutBagInput>
}

export type TiddlerUpdateManyWithWhereWithoutBagInput = {
  where: Prisma.TiddlerScalarWhereInput
  data: Prisma.XOR<Prisma.TiddlerUpdateManyMutationInput, Prisma.TiddlerUncheckedUpdateManyWithoutBagInput>
}

export type TiddlerScalarWhereInput = {
  AND?: Prisma.TiddlerScalarWhereInput | Prisma.TiddlerScalarWhereInput[]
  OR?: Prisma.TiddlerScalarWhereInput[]
  NOT?: Prisma.TiddlerScalarWhereInput | Prisma.TiddlerScalarWhereInput[]
  bag_id?: Prisma.StringFilter<"Tiddler"> | string
  title?: Prisma.StringFilter<"Tiddler"> | string
  created?: Prisma.DateTimeFilter<"Tiddler"> | Date | string
  updated?: Prisma.DateTimeFilter<"Tiddler"> | Date | string
  revision?: Prisma.BigIntFilter<"Tiddler"> | bigint | number
  fields?: Prisma.JsonFilter<"Tiddler">
}

export type TiddlerCreateManyBagInput = {
  title: string
  created?: Date | string
  updated?: Date | string
  revision?: bigint | number
  fields:PrismaJson.Tiddler_fields
}

export type TiddlerUpdateWithoutBagInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revision?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fields?:PrismaJson.Tiddler_fields
}

export type TiddlerUncheckedUpdateWithoutBagInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revision?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fields?:PrismaJson.Tiddler_fields
}

export type TiddlerUncheckedUpdateManyWithoutBagInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revision?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  fields?:PrismaJson.Tiddler_fields
}



export type TiddlerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  title?: boolean
  created?: boolean
  updated?: boolean
  revision?: boolean
  fields?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddler"]>

export type TiddlerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  title?: boolean
  created?: boolean
  updated?: boolean
  revision?: boolean
  fields?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddler"]>

export type TiddlerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bag_id?: boolean
  title?: boolean
  created?: boolean
  updated?: boolean
  revision?: boolean
  fields?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddler"]>

export type TiddlerSelectScalar = {
  bag_id?: boolean
  title?: boolean
  created?: boolean
  updated?: boolean
  revision?: boolean
  fields?: boolean
}

export type TiddlerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"bag_id" | "title" | "created" | "updated" | "revision" | "fields", ExtArgs["result"]["tiddler"]>
export type TiddlerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}
export type TiddlerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}
export type TiddlerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}

export type $TiddlerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tiddler"
  objects: {
    bag: Prisma.$BagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    bag_id: string
    title: string
    created: Date
    updated: Date
    revision: bigint
    /**
     * [Tiddler_fields]
     */
    fields:PrismaJson.Tiddler_fields
  }, ExtArgs["result"]["tiddler"]>
  composites: {}
}

export type TiddlerGetPayload<S extends boolean | null | undefined | TiddlerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TiddlerPayload, S>

export type TiddlerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TiddlerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TiddlerCountAggregateInputType | true
  }

export interface TiddlerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tiddler'], meta: { name: 'Tiddler' } }
  /**
   * Find zero or one Tiddler that matches the filter.
   * @param {TiddlerFindUniqueArgs} args - Arguments to find a Tiddler
   * @example
   * // Get one Tiddler
   * const tiddler = await prisma.tiddler.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TiddlerFindUniqueArgs>(args: Prisma.SelectSubset<T, TiddlerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tiddler that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TiddlerFindUniqueOrThrowArgs} args - Arguments to find a Tiddler
   * @example
   * // Get one Tiddler
   * const tiddler = await prisma.tiddler.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TiddlerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TiddlerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tiddler that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerFindFirstArgs} args - Arguments to find a Tiddler
   * @example
   * // Get one Tiddler
   * const tiddler = await prisma.tiddler.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TiddlerFindFirstArgs>(args?: Prisma.SelectSubset<T, TiddlerFindFirstArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tiddler that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerFindFirstOrThrowArgs} args - Arguments to find a Tiddler
   * @example
   * // Get one Tiddler
   * const tiddler = await prisma.tiddler.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TiddlerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TiddlerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tiddlers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tiddlers
   * const tiddlers = await prisma.tiddler.findMany()
   * 
   * // Get first 10 Tiddlers
   * const tiddlers = await prisma.tiddler.findMany({ take: 10 })
   * 
   * // Only select the `bag_id`
   * const tiddlerWithBag_idOnly = await prisma.tiddler.findMany({ select: { bag_id: true } })
   * 
   */
  findMany<T extends TiddlerFindManyArgs>(args?: Prisma.SelectSubset<T, TiddlerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tiddler.
   * @param {TiddlerCreateArgs} args - Arguments to create a Tiddler.
   * @example
   * // Create one Tiddler
   * const Tiddler = await prisma.tiddler.create({
   *   data: {
   *     // ... data to create a Tiddler
   *   }
   * })
   * 
   */
  create<T extends TiddlerCreateArgs>(args: Prisma.SelectSubset<T, TiddlerCreateArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tiddlers.
   * @param {TiddlerCreateManyArgs} args - Arguments to create many Tiddlers.
   * @example
   * // Create many Tiddlers
   * const tiddler = await prisma.tiddler.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TiddlerCreateManyArgs>(args?: Prisma.SelectSubset<T, TiddlerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tiddlers and returns the data saved in the database.
   * @param {TiddlerCreateManyAndReturnArgs} args - Arguments to create many Tiddlers.
   * @example
   * // Create many Tiddlers
   * const tiddler = await prisma.tiddler.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tiddlers and only return the `bag_id`
   * const tiddlerWithBag_idOnly = await prisma.tiddler.createManyAndReturn({
   *   select: { bag_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TiddlerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TiddlerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tiddler.
   * @param {TiddlerDeleteArgs} args - Arguments to delete one Tiddler.
   * @example
   * // Delete one Tiddler
   * const Tiddler = await prisma.tiddler.delete({
   *   where: {
   *     // ... filter to delete one Tiddler
   *   }
   * })
   * 
   */
  delete<T extends TiddlerDeleteArgs>(args: Prisma.SelectSubset<T, TiddlerDeleteArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tiddler.
   * @param {TiddlerUpdateArgs} args - Arguments to update one Tiddler.
   * @example
   * // Update one Tiddler
   * const tiddler = await prisma.tiddler.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TiddlerUpdateArgs>(args: Prisma.SelectSubset<T, TiddlerUpdateArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tiddlers.
   * @param {TiddlerDeleteManyArgs} args - Arguments to filter Tiddlers to delete.
   * @example
   * // Delete a few Tiddlers
   * const { count } = await prisma.tiddler.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TiddlerDeleteManyArgs>(args?: Prisma.SelectSubset<T, TiddlerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tiddlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tiddlers
   * const tiddler = await prisma.tiddler.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TiddlerUpdateManyArgs>(args: Prisma.SelectSubset<T, TiddlerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tiddlers and returns the data updated in the database.
   * @param {TiddlerUpdateManyAndReturnArgs} args - Arguments to update many Tiddlers.
   * @example
   * // Update many Tiddlers
   * const tiddler = await prisma.tiddler.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tiddlers and only return the `bag_id`
   * const tiddlerWithBag_idOnly = await prisma.tiddler.updateManyAndReturn({
   *   select: { bag_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TiddlerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TiddlerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tiddler.
   * @param {TiddlerUpsertArgs} args - Arguments to update or create a Tiddler.
   * @example
   * // Update or create a Tiddler
   * const tiddler = await prisma.tiddler.upsert({
   *   create: {
   *     // ... data to create a Tiddler
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tiddler we want to update
   *   }
   * })
   */
  upsert<T extends TiddlerUpsertArgs>(args: Prisma.SelectSubset<T, TiddlerUpsertArgs<ExtArgs>>): Prisma.Prisma__TiddlerClient<runtime.Types.Result.GetResult<Prisma.$TiddlerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tiddlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerCountArgs} args - Arguments to filter Tiddlers to count.
   * @example
   * // Count the number of Tiddlers
   * const count = await prisma.tiddler.count({
   *   where: {
   *     // ... the filter for the Tiddlers we want to count
   *   }
   * })
  **/
  count<T extends TiddlerCountArgs>(
    args?: Prisma.Subset<T, TiddlerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TiddlerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tiddler.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TiddlerAggregateArgs>(args: Prisma.Subset<T, TiddlerAggregateArgs>): Prisma.PrismaPromise<GetTiddlerAggregateType<T>>

  /**
   * Group by Tiddler.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TiddlerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TiddlerGroupByArgs['orderBy'] }
      : { orderBy?: TiddlerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TiddlerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTiddlerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tiddler model
 */
readonly fields: TiddlerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tiddler.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TiddlerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bag<T extends Prisma.BagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BagDefaultArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tiddler model
 */
export interface TiddlerFieldRefs {
  readonly bag_id: Prisma.FieldRef<"Tiddler", 'String'>
  readonly title: Prisma.FieldRef<"Tiddler", 'String'>
  readonly created: Prisma.FieldRef<"Tiddler", 'DateTime'>
  readonly updated: Prisma.FieldRef<"Tiddler", 'DateTime'>
  readonly revision: Prisma.FieldRef<"Tiddler", 'BigInt'>
  readonly fields: Prisma.FieldRef<"Tiddler", 'Json'>
}
    

// Custom InputTypes
/**
 * Tiddler findUnique
 */
export type TiddlerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * Filter, which Tiddler to fetch.
   */
  where: Prisma.TiddlerWhereUniqueInput
}

/**
 * Tiddler findUniqueOrThrow
 */
export type TiddlerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * Filter, which Tiddler to fetch.
   */
  where: Prisma.TiddlerWhereUniqueInput
}

/**
 * Tiddler findFirst
 */
export type TiddlerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * Filter, which Tiddler to fetch.
   */
  where?: Prisma.TiddlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlerOrderByWithRelationInput | Prisma.TiddlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tiddlers.
   */
  cursor?: Prisma.TiddlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tiddlers.
   */
  distinct?: Prisma.TiddlerScalarFieldEnum | Prisma.TiddlerScalarFieldEnum[]
}

/**
 * Tiddler findFirstOrThrow
 */
export type TiddlerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * Filter, which Tiddler to fetch.
   */
  where?: Prisma.TiddlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlerOrderByWithRelationInput | Prisma.TiddlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tiddlers.
   */
  cursor?: Prisma.TiddlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tiddlers.
   */
  distinct?: Prisma.TiddlerScalarFieldEnum | Prisma.TiddlerScalarFieldEnum[]
}

/**
 * Tiddler findMany
 */
export type TiddlerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * Filter, which Tiddlers to fetch.
   */
  where?: Prisma.TiddlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tiddlers to fetch.
   */
  orderBy?: Prisma.TiddlerOrderByWithRelationInput | Prisma.TiddlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tiddlers.
   */
  cursor?: Prisma.TiddlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tiddlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tiddlers.
   */
  skip?: number
  distinct?: Prisma.TiddlerScalarFieldEnum | Prisma.TiddlerScalarFieldEnum[]
}

/**
 * Tiddler create
 */
export type TiddlerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * The data needed to create a Tiddler.
   */
  data: Prisma.XOR<Prisma.TiddlerCreateInput, Prisma.TiddlerUncheckedCreateInput>
}

/**
 * Tiddler createMany
 */
export type TiddlerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tiddlers.
   */
  data: Prisma.TiddlerCreateManyInput | Prisma.TiddlerCreateManyInput[]
}

/**
 * Tiddler createManyAndReturn
 */
export type TiddlerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * The data used to create many Tiddlers.
   */
  data: Prisma.TiddlerCreateManyInput | Prisma.TiddlerCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Tiddler update
 */
export type TiddlerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * The data needed to update a Tiddler.
   */
  data: Prisma.XOR<Prisma.TiddlerUpdateInput, Prisma.TiddlerUncheckedUpdateInput>
  /**
   * Choose, which Tiddler to update.
   */
  where: Prisma.TiddlerWhereUniqueInput
}

/**
 * Tiddler updateMany
 */
export type TiddlerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tiddlers.
   */
  data: Prisma.XOR<Prisma.TiddlerUpdateManyMutationInput, Prisma.TiddlerUncheckedUpdateManyInput>
  /**
   * Filter which Tiddlers to update
   */
  where?: Prisma.TiddlerWhereInput
  /**
   * Limit how many Tiddlers to update.
   */
  limit?: number
}

/**
 * Tiddler updateManyAndReturn
 */
export type TiddlerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * The data used to update Tiddlers.
   */
  data: Prisma.XOR<Prisma.TiddlerUpdateManyMutationInput, Prisma.TiddlerUncheckedUpdateManyInput>
  /**
   * Filter which Tiddlers to update
   */
  where?: Prisma.TiddlerWhereInput
  /**
   * Limit how many Tiddlers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Tiddler upsert
 */
export type TiddlerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * The filter to search for the Tiddler to update in case it exists.
   */
  where: Prisma.TiddlerWhereUniqueInput
  /**
   * In case the Tiddler found by the `where` argument doesn't exist, create a new Tiddler with this data.
   */
  create: Prisma.XOR<Prisma.TiddlerCreateInput, Prisma.TiddlerUncheckedCreateInput>
  /**
   * In case the Tiddler was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TiddlerUpdateInput, Prisma.TiddlerUncheckedUpdateInput>
}

/**
 * Tiddler delete
 */
export type TiddlerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
  /**
   * Filter which Tiddler to delete.
   */
  where: Prisma.TiddlerWhereUniqueInput
}

/**
 * Tiddler deleteMany
 */
export type TiddlerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tiddlers to delete
   */
  where?: Prisma.TiddlerWhereInput
  /**
   * Limit how many Tiddlers to delete.
   */
  limit?: number
}

/**
 * Tiddler without action
 */
export type TiddlerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tiddler
   */
  select?: Prisma.TiddlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tiddler
   */
  omit?: Prisma.TiddlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerInclude<ExtArgs> | null
}
