
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TiddlerEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TiddlerEvent
 * 
 */
export type TiddlerEventModel = runtime.Types.Result.DefaultSelection<Prisma.$TiddlerEventPayload>

export type AggregateTiddlerEvent = {
  _count: TiddlerEventCountAggregateOutputType | null
  _avg: TiddlerEventAvgAggregateOutputType | null
  _sum: TiddlerEventSumAggregateOutputType | null
  _min: TiddlerEventMinAggregateOutputType | null
  _max: TiddlerEventMaxAggregateOutputType | null
}

export type TiddlerEventAvgAggregateOutputType = {
  seq: number | null
}

export type TiddlerEventSumAggregateOutputType = {
  seq: number | null
}

export type TiddlerEventMinAggregateOutputType = {
  seq: number | null
  bag_id: string | null
  title: string | null
  type: $Enums.TiddlerEventType | null
}

export type TiddlerEventMaxAggregateOutputType = {
  seq: number | null
  bag_id: string | null
  title: string | null
  type: $Enums.TiddlerEventType | null
}

export type TiddlerEventCountAggregateOutputType = {
  seq: number
  bag_id: number
  title: number
  type: number
  _all: number
}


export type TiddlerEventAvgAggregateInputType = {
  seq?: true
}

export type TiddlerEventSumAggregateInputType = {
  seq?: true
}

export type TiddlerEventMinAggregateInputType = {
  seq?: true
  bag_id?: true
  title?: true
  type?: true
}

export type TiddlerEventMaxAggregateInputType = {
  seq?: true
  bag_id?: true
  title?: true
  type?: true
}

export type TiddlerEventCountAggregateInputType = {
  seq?: true
  bag_id?: true
  title?: true
  type?: true
  _all?: true
}

export type TiddlerEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TiddlerEvent to aggregate.
   */
  where?: Prisma.TiddlerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TiddlerEvents to fetch.
   */
  orderBy?: Prisma.TiddlerEventOrderByWithRelationInput | Prisma.TiddlerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TiddlerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TiddlerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TiddlerEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TiddlerEvents
  **/
  _count?: true | TiddlerEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TiddlerEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TiddlerEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TiddlerEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TiddlerEventMaxAggregateInputType
}

export type GetTiddlerEventAggregateType<T extends TiddlerEventAggregateArgs> = {
      [P in keyof T & keyof AggregateTiddlerEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTiddlerEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateTiddlerEvent[P]>
}




export type TiddlerEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TiddlerEventWhereInput
  orderBy?: Prisma.TiddlerEventOrderByWithAggregationInput | Prisma.TiddlerEventOrderByWithAggregationInput[]
  by: Prisma.TiddlerEventScalarFieldEnum[] | Prisma.TiddlerEventScalarFieldEnum
  having?: Prisma.TiddlerEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TiddlerEventCountAggregateInputType | true
  _avg?: TiddlerEventAvgAggregateInputType
  _sum?: TiddlerEventSumAggregateInputType
  _min?: TiddlerEventMinAggregateInputType
  _max?: TiddlerEventMaxAggregateInputType
}

export type TiddlerEventGroupByOutputType = {
  seq: number
  bag_id: string
  title: string
  type: $Enums.TiddlerEventType
  _count: TiddlerEventCountAggregateOutputType | null
  _avg: TiddlerEventAvgAggregateOutputType | null
  _sum: TiddlerEventSumAggregateOutputType | null
  _min: TiddlerEventMinAggregateOutputType | null
  _max: TiddlerEventMaxAggregateOutputType | null
}

export type GetTiddlerEventGroupByPayload<T extends TiddlerEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TiddlerEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TiddlerEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TiddlerEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TiddlerEventGroupByOutputType[P]>
      }
    >
  >



export type TiddlerEventWhereInput = {
  AND?: Prisma.TiddlerEventWhereInput | Prisma.TiddlerEventWhereInput[]
  OR?: Prisma.TiddlerEventWhereInput[]
  NOT?: Prisma.TiddlerEventWhereInput | Prisma.TiddlerEventWhereInput[]
  seq?: Prisma.IntFilter<"TiddlerEvent"> | number
  bag_id?: Prisma.StringFilter<"TiddlerEvent"> | string
  title?: Prisma.StringFilter<"TiddlerEvent"> | string
  type?: Prisma.EnumTiddlerEventTypeFilter<"TiddlerEvent"> | $Enums.TiddlerEventType
  bag?: Prisma.XOR<Prisma.BagScalarRelationFilter, Prisma.BagWhereInput>
}

export type TiddlerEventOrderByWithRelationInput = {
  seq?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  bag?: Prisma.BagOrderByWithRelationInput
}

export type TiddlerEventWhereUniqueInput = Prisma.AtLeast<{
  seq?: number
  AND?: Prisma.TiddlerEventWhereInput | Prisma.TiddlerEventWhereInput[]
  OR?: Prisma.TiddlerEventWhereInput[]
  NOT?: Prisma.TiddlerEventWhereInput | Prisma.TiddlerEventWhereInput[]
  bag_id?: Prisma.StringFilter<"TiddlerEvent"> | string
  title?: Prisma.StringFilter<"TiddlerEvent"> | string
  type?: Prisma.EnumTiddlerEventTypeFilter<"TiddlerEvent"> | $Enums.TiddlerEventType
  bag?: Prisma.XOR<Prisma.BagScalarRelationFilter, Prisma.BagWhereInput>
}, "seq">

export type TiddlerEventOrderByWithAggregationInput = {
  seq?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
  _count?: Prisma.TiddlerEventCountOrderByAggregateInput
  _avg?: Prisma.TiddlerEventAvgOrderByAggregateInput
  _max?: Prisma.TiddlerEventMaxOrderByAggregateInput
  _min?: Prisma.TiddlerEventMinOrderByAggregateInput
  _sum?: Prisma.TiddlerEventSumOrderByAggregateInput
}

export type TiddlerEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.TiddlerEventScalarWhereWithAggregatesInput | Prisma.TiddlerEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.TiddlerEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TiddlerEventScalarWhereWithAggregatesInput | Prisma.TiddlerEventScalarWhereWithAggregatesInput[]
  seq?: Prisma.IntWithAggregatesFilter<"TiddlerEvent"> | number
  bag_id?: Prisma.StringWithAggregatesFilter<"TiddlerEvent"> | string
  title?: Prisma.StringWithAggregatesFilter<"TiddlerEvent"> | string
  type?: Prisma.EnumTiddlerEventTypeWithAggregatesFilter<"TiddlerEvent"> | $Enums.TiddlerEventType
}

export type TiddlerEventCreateInput = {
  title: string
  type: $Enums.TiddlerEventType
  bag: Prisma.BagCreateNestedOneWithoutTiddler_eventsInput
}

export type TiddlerEventUncheckedCreateInput = {
  seq?: number
  bag_id: string
  title: string
  type: $Enums.TiddlerEventType
}

export type TiddlerEventUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTiddlerEventTypeFieldUpdateOperationsInput | $Enums.TiddlerEventType
  bag?: Prisma.BagUpdateOneRequiredWithoutTiddler_eventsNestedInput
}

export type TiddlerEventUncheckedUpdateInput = {
  seq?: Prisma.IntFieldUpdateOperationsInput | number
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTiddlerEventTypeFieldUpdateOperationsInput | $Enums.TiddlerEventType
}

export type TiddlerEventCreateManyInput = {
  seq?: number
  bag_id: string
  title: string
  type: $Enums.TiddlerEventType
}

export type TiddlerEventUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTiddlerEventTypeFieldUpdateOperationsInput | $Enums.TiddlerEventType
}

export type TiddlerEventUncheckedUpdateManyInput = {
  seq?: Prisma.IntFieldUpdateOperationsInput | number
  bag_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTiddlerEventTypeFieldUpdateOperationsInput | $Enums.TiddlerEventType
}

export type TiddlerEventListRelationFilter = {
  every?: Prisma.TiddlerEventWhereInput
  some?: Prisma.TiddlerEventWhereInput
  none?: Prisma.TiddlerEventWhereInput
}

export type TiddlerEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TiddlerEventCountOrderByAggregateInput = {
  seq?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type TiddlerEventAvgOrderByAggregateInput = {
  seq?: Prisma.SortOrder
}

export type TiddlerEventMaxOrderByAggregateInput = {
  seq?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type TiddlerEventMinOrderByAggregateInput = {
  seq?: Prisma.SortOrder
  bag_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type TiddlerEventSumOrderByAggregateInput = {
  seq?: Prisma.SortOrder
}

export type TiddlerEventCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.TiddlerEventCreateWithoutBagInput, Prisma.TiddlerEventUncheckedCreateWithoutBagInput> | Prisma.TiddlerEventCreateWithoutBagInput[] | Prisma.TiddlerEventUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerEventCreateOrConnectWithoutBagInput | Prisma.TiddlerEventCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.TiddlerEventCreateManyBagInputEnvelope
  connect?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
}

export type TiddlerEventUncheckedCreateNestedManyWithoutBagInput = {
  create?: Prisma.XOR<Prisma.TiddlerEventCreateWithoutBagInput, Prisma.TiddlerEventUncheckedCreateWithoutBagInput> | Prisma.TiddlerEventCreateWithoutBagInput[] | Prisma.TiddlerEventUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerEventCreateOrConnectWithoutBagInput | Prisma.TiddlerEventCreateOrConnectWithoutBagInput[]
  createMany?: Prisma.TiddlerEventCreateManyBagInputEnvelope
  connect?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
}

export type TiddlerEventUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.TiddlerEventCreateWithoutBagInput, Prisma.TiddlerEventUncheckedCreateWithoutBagInput> | Prisma.TiddlerEventCreateWithoutBagInput[] | Prisma.TiddlerEventUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerEventCreateOrConnectWithoutBagInput | Prisma.TiddlerEventCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.TiddlerEventUpsertWithWhereUniqueWithoutBagInput | Prisma.TiddlerEventUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.TiddlerEventCreateManyBagInputEnvelope
  set?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  disconnect?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  delete?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  connect?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  update?: Prisma.TiddlerEventUpdateWithWhereUniqueWithoutBagInput | Prisma.TiddlerEventUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.TiddlerEventUpdateManyWithWhereWithoutBagInput | Prisma.TiddlerEventUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.TiddlerEventScalarWhereInput | Prisma.TiddlerEventScalarWhereInput[]
}

export type TiddlerEventUncheckedUpdateManyWithoutBagNestedInput = {
  create?: Prisma.XOR<Prisma.TiddlerEventCreateWithoutBagInput, Prisma.TiddlerEventUncheckedCreateWithoutBagInput> | Prisma.TiddlerEventCreateWithoutBagInput[] | Prisma.TiddlerEventUncheckedCreateWithoutBagInput[]
  connectOrCreate?: Prisma.TiddlerEventCreateOrConnectWithoutBagInput | Prisma.TiddlerEventCreateOrConnectWithoutBagInput[]
  upsert?: Prisma.TiddlerEventUpsertWithWhereUniqueWithoutBagInput | Prisma.TiddlerEventUpsertWithWhereUniqueWithoutBagInput[]
  createMany?: Prisma.TiddlerEventCreateManyBagInputEnvelope
  set?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  disconnect?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  delete?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  connect?: Prisma.TiddlerEventWhereUniqueInput | Prisma.TiddlerEventWhereUniqueInput[]
  update?: Prisma.TiddlerEventUpdateWithWhereUniqueWithoutBagInput | Prisma.TiddlerEventUpdateWithWhereUniqueWithoutBagInput[]
  updateMany?: Prisma.TiddlerEventUpdateManyWithWhereWithoutBagInput | Prisma.TiddlerEventUpdateManyWithWhereWithoutBagInput[]
  deleteMany?: Prisma.TiddlerEventScalarWhereInput | Prisma.TiddlerEventScalarWhereInput[]
}

export type EnumTiddlerEventTypeFieldUpdateOperationsInput = {
  set?: $Enums.TiddlerEventType
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TiddlerEventCreateWithoutBagInput = {
  title: string
  type: $Enums.TiddlerEventType
}

export type TiddlerEventUncheckedCreateWithoutBagInput = {
  seq?: number
  title: string
  type: $Enums.TiddlerEventType
}

export type TiddlerEventCreateOrConnectWithoutBagInput = {
  where: Prisma.TiddlerEventWhereUniqueInput
  create: Prisma.XOR<Prisma.TiddlerEventCreateWithoutBagInput, Prisma.TiddlerEventUncheckedCreateWithoutBagInput>
}

export type TiddlerEventCreateManyBagInputEnvelope = {
  data: Prisma.TiddlerEventCreateManyBagInput | Prisma.TiddlerEventCreateManyBagInput[]
}

export type TiddlerEventUpsertWithWhereUniqueWithoutBagInput = {
  where: Prisma.TiddlerEventWhereUniqueInput
  update: Prisma.XOR<Prisma.TiddlerEventUpdateWithoutBagInput, Prisma.TiddlerEventUncheckedUpdateWithoutBagInput>
  create: Prisma.XOR<Prisma.TiddlerEventCreateWithoutBagInput, Prisma.TiddlerEventUncheckedCreateWithoutBagInput>
}

export type TiddlerEventUpdateWithWhereUniqueWithoutBagInput = {
  where: Prisma.TiddlerEventWhereUniqueInput
  data: Prisma.XOR<Prisma.TiddlerEventUpdateWithoutBagInput, Prisma.TiddlerEventUncheckedUpdateWithoutBagInput>
}

export type TiddlerEventUpdateManyWithWhereWithoutBagInput = {
  where: Prisma.TiddlerEventScalarWhereInput
  data: Prisma.XOR<Prisma.TiddlerEventUpdateManyMutationInput, Prisma.TiddlerEventUncheckedUpdateManyWithoutBagInput>
}

export type TiddlerEventScalarWhereInput = {
  AND?: Prisma.TiddlerEventScalarWhereInput | Prisma.TiddlerEventScalarWhereInput[]
  OR?: Prisma.TiddlerEventScalarWhereInput[]
  NOT?: Prisma.TiddlerEventScalarWhereInput | Prisma.TiddlerEventScalarWhereInput[]
  seq?: Prisma.IntFilter<"TiddlerEvent"> | number
  bag_id?: Prisma.StringFilter<"TiddlerEvent"> | string
  title?: Prisma.StringFilter<"TiddlerEvent"> | string
  type?: Prisma.EnumTiddlerEventTypeFilter<"TiddlerEvent"> | $Enums.TiddlerEventType
}

export type TiddlerEventCreateManyBagInput = {
  seq?: number
  title: string
  type: $Enums.TiddlerEventType
}

export type TiddlerEventUpdateWithoutBagInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTiddlerEventTypeFieldUpdateOperationsInput | $Enums.TiddlerEventType
}

export type TiddlerEventUncheckedUpdateWithoutBagInput = {
  seq?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTiddlerEventTypeFieldUpdateOperationsInput | $Enums.TiddlerEventType
}

export type TiddlerEventUncheckedUpdateManyWithoutBagInput = {
  seq?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumTiddlerEventTypeFieldUpdateOperationsInput | $Enums.TiddlerEventType
}



export type TiddlerEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  seq?: boolean
  bag_id?: boolean
  title?: boolean
  type?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddlerEvent"]>

export type TiddlerEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  seq?: boolean
  bag_id?: boolean
  title?: boolean
  type?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddlerEvent"]>

export type TiddlerEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  seq?: boolean
  bag_id?: boolean
  title?: boolean
  type?: boolean
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tiddlerEvent"]>

export type TiddlerEventSelectScalar = {
  seq?: boolean
  bag_id?: boolean
  title?: boolean
  type?: boolean
}

export type TiddlerEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"seq" | "bag_id" | "title" | "type", ExtArgs["result"]["tiddlerEvent"]>
export type TiddlerEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}
export type TiddlerEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}
export type TiddlerEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bag?: boolean | Prisma.BagDefaultArgs<ExtArgs>
}

export type $TiddlerEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TiddlerEvent"
  objects: {
    bag: Prisma.$BagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    seq: number
    bag_id: string
    title: string
    type: $Enums.TiddlerEventType
  }, ExtArgs["result"]["tiddlerEvent"]>
  composites: {}
}

export type TiddlerEventGetPayload<S extends boolean | null | undefined | TiddlerEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload, S>

export type TiddlerEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TiddlerEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TiddlerEventCountAggregateInputType | true
  }

export interface TiddlerEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TiddlerEvent'], meta: { name: 'TiddlerEvent' } }
  /**
   * Find zero or one TiddlerEvent that matches the filter.
   * @param {TiddlerEventFindUniqueArgs} args - Arguments to find a TiddlerEvent
   * @example
   * // Get one TiddlerEvent
   * const tiddlerEvent = await prisma.tiddlerEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TiddlerEventFindUniqueArgs>(args: Prisma.SelectSubset<T, TiddlerEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TiddlerEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TiddlerEventFindUniqueOrThrowArgs} args - Arguments to find a TiddlerEvent
   * @example
   * // Get one TiddlerEvent
   * const tiddlerEvent = await prisma.tiddlerEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TiddlerEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TiddlerEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TiddlerEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerEventFindFirstArgs} args - Arguments to find a TiddlerEvent
   * @example
   * // Get one TiddlerEvent
   * const tiddlerEvent = await prisma.tiddlerEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TiddlerEventFindFirstArgs>(args?: Prisma.SelectSubset<T, TiddlerEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TiddlerEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerEventFindFirstOrThrowArgs} args - Arguments to find a TiddlerEvent
   * @example
   * // Get one TiddlerEvent
   * const tiddlerEvent = await prisma.tiddlerEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TiddlerEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TiddlerEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TiddlerEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TiddlerEvents
   * const tiddlerEvents = await prisma.tiddlerEvent.findMany()
   * 
   * // Get first 10 TiddlerEvents
   * const tiddlerEvents = await prisma.tiddlerEvent.findMany({ take: 10 })
   * 
   * // Only select the `seq`
   * const tiddlerEventWithSeqOnly = await prisma.tiddlerEvent.findMany({ select: { seq: true } })
   * 
   */
  findMany<T extends TiddlerEventFindManyArgs>(args?: Prisma.SelectSubset<T, TiddlerEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TiddlerEvent.
   * @param {TiddlerEventCreateArgs} args - Arguments to create a TiddlerEvent.
   * @example
   * // Create one TiddlerEvent
   * const TiddlerEvent = await prisma.tiddlerEvent.create({
   *   data: {
   *     // ... data to create a TiddlerEvent
   *   }
   * })
   * 
   */
  create<T extends TiddlerEventCreateArgs>(args: Prisma.SelectSubset<T, TiddlerEventCreateArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TiddlerEvents.
   * @param {TiddlerEventCreateManyArgs} args - Arguments to create many TiddlerEvents.
   * @example
   * // Create many TiddlerEvents
   * const tiddlerEvent = await prisma.tiddlerEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TiddlerEventCreateManyArgs>(args?: Prisma.SelectSubset<T, TiddlerEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TiddlerEvents and returns the data saved in the database.
   * @param {TiddlerEventCreateManyAndReturnArgs} args - Arguments to create many TiddlerEvents.
   * @example
   * // Create many TiddlerEvents
   * const tiddlerEvent = await prisma.tiddlerEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TiddlerEvents and only return the `seq`
   * const tiddlerEventWithSeqOnly = await prisma.tiddlerEvent.createManyAndReturn({
   *   select: { seq: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TiddlerEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TiddlerEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TiddlerEvent.
   * @param {TiddlerEventDeleteArgs} args - Arguments to delete one TiddlerEvent.
   * @example
   * // Delete one TiddlerEvent
   * const TiddlerEvent = await prisma.tiddlerEvent.delete({
   *   where: {
   *     // ... filter to delete one TiddlerEvent
   *   }
   * })
   * 
   */
  delete<T extends TiddlerEventDeleteArgs>(args: Prisma.SelectSubset<T, TiddlerEventDeleteArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TiddlerEvent.
   * @param {TiddlerEventUpdateArgs} args - Arguments to update one TiddlerEvent.
   * @example
   * // Update one TiddlerEvent
   * const tiddlerEvent = await prisma.tiddlerEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TiddlerEventUpdateArgs>(args: Prisma.SelectSubset<T, TiddlerEventUpdateArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TiddlerEvents.
   * @param {TiddlerEventDeleteManyArgs} args - Arguments to filter TiddlerEvents to delete.
   * @example
   * // Delete a few TiddlerEvents
   * const { count } = await prisma.tiddlerEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TiddlerEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, TiddlerEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TiddlerEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TiddlerEvents
   * const tiddlerEvent = await prisma.tiddlerEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TiddlerEventUpdateManyArgs>(args: Prisma.SelectSubset<T, TiddlerEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TiddlerEvents and returns the data updated in the database.
   * @param {TiddlerEventUpdateManyAndReturnArgs} args - Arguments to update many TiddlerEvents.
   * @example
   * // Update many TiddlerEvents
   * const tiddlerEvent = await prisma.tiddlerEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TiddlerEvents and only return the `seq`
   * const tiddlerEventWithSeqOnly = await prisma.tiddlerEvent.updateManyAndReturn({
   *   select: { seq: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TiddlerEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TiddlerEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TiddlerEvent.
   * @param {TiddlerEventUpsertArgs} args - Arguments to update or create a TiddlerEvent.
   * @example
   * // Update or create a TiddlerEvent
   * const tiddlerEvent = await prisma.tiddlerEvent.upsert({
   *   create: {
   *     // ... data to create a TiddlerEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TiddlerEvent we want to update
   *   }
   * })
   */
  upsert<T extends TiddlerEventUpsertArgs>(args: Prisma.SelectSubset<T, TiddlerEventUpsertArgs<ExtArgs>>): Prisma.Prisma__TiddlerEventClient<runtime.Types.Result.GetResult<Prisma.$TiddlerEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TiddlerEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerEventCountArgs} args - Arguments to filter TiddlerEvents to count.
   * @example
   * // Count the number of TiddlerEvents
   * const count = await prisma.tiddlerEvent.count({
   *   where: {
   *     // ... the filter for the TiddlerEvents we want to count
   *   }
   * })
  **/
  count<T extends TiddlerEventCountArgs>(
    args?: Prisma.Subset<T, TiddlerEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TiddlerEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TiddlerEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TiddlerEventAggregateArgs>(args: Prisma.Subset<T, TiddlerEventAggregateArgs>): Prisma.PrismaPromise<GetTiddlerEventAggregateType<T>>

  /**
   * Group by TiddlerEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TiddlerEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TiddlerEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TiddlerEventGroupByArgs['orderBy'] }
      : { orderBy?: TiddlerEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TiddlerEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTiddlerEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TiddlerEvent model
 */
readonly fields: TiddlerEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TiddlerEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TiddlerEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bag<T extends Prisma.BagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BagDefaultArgs<ExtArgs>>): Prisma.Prisma__BagClient<runtime.Types.Result.GetResult<Prisma.$BagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TiddlerEvent model
 */
export interface TiddlerEventFieldRefs {
  readonly seq: Prisma.FieldRef<"TiddlerEvent", 'Int'>
  readonly bag_id: Prisma.FieldRef<"TiddlerEvent", 'String'>
  readonly title: Prisma.FieldRef<"TiddlerEvent", 'String'>
  readonly type: Prisma.FieldRef<"TiddlerEvent", 'TiddlerEventType'>
}
    

// Custom InputTypes
/**
 * TiddlerEvent findUnique
 */
export type TiddlerEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * Filter, which TiddlerEvent to fetch.
   */
  where: Prisma.TiddlerEventWhereUniqueInput
}

/**
 * TiddlerEvent findUniqueOrThrow
 */
export type TiddlerEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * Filter, which TiddlerEvent to fetch.
   */
  where: Prisma.TiddlerEventWhereUniqueInput
}

/**
 * TiddlerEvent findFirst
 */
export type TiddlerEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * Filter, which TiddlerEvent to fetch.
   */
  where?: Prisma.TiddlerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TiddlerEvents to fetch.
   */
  orderBy?: Prisma.TiddlerEventOrderByWithRelationInput | Prisma.TiddlerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TiddlerEvents.
   */
  cursor?: Prisma.TiddlerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TiddlerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TiddlerEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TiddlerEvents.
   */
  distinct?: Prisma.TiddlerEventScalarFieldEnum | Prisma.TiddlerEventScalarFieldEnum[]
}

/**
 * TiddlerEvent findFirstOrThrow
 */
export type TiddlerEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * Filter, which TiddlerEvent to fetch.
   */
  where?: Prisma.TiddlerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TiddlerEvents to fetch.
   */
  orderBy?: Prisma.TiddlerEventOrderByWithRelationInput | Prisma.TiddlerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TiddlerEvents.
   */
  cursor?: Prisma.TiddlerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TiddlerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TiddlerEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TiddlerEvents.
   */
  distinct?: Prisma.TiddlerEventScalarFieldEnum | Prisma.TiddlerEventScalarFieldEnum[]
}

/**
 * TiddlerEvent findMany
 */
export type TiddlerEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * Filter, which TiddlerEvents to fetch.
   */
  where?: Prisma.TiddlerEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TiddlerEvents to fetch.
   */
  orderBy?: Prisma.TiddlerEventOrderByWithRelationInput | Prisma.TiddlerEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TiddlerEvents.
   */
  cursor?: Prisma.TiddlerEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TiddlerEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TiddlerEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TiddlerEvents.
   */
  distinct?: Prisma.TiddlerEventScalarFieldEnum | Prisma.TiddlerEventScalarFieldEnum[]
}

/**
 * TiddlerEvent create
 */
export type TiddlerEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * The data needed to create a TiddlerEvent.
   */
  data: Prisma.XOR<Prisma.TiddlerEventCreateInput, Prisma.TiddlerEventUncheckedCreateInput>
}

/**
 * TiddlerEvent createMany
 */
export type TiddlerEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TiddlerEvents.
   */
  data: Prisma.TiddlerEventCreateManyInput | Prisma.TiddlerEventCreateManyInput[]
}

/**
 * TiddlerEvent createManyAndReturn
 */
export type TiddlerEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * The data used to create many TiddlerEvents.
   */
  data: Prisma.TiddlerEventCreateManyInput | Prisma.TiddlerEventCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TiddlerEvent update
 */
export type TiddlerEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * The data needed to update a TiddlerEvent.
   */
  data: Prisma.XOR<Prisma.TiddlerEventUpdateInput, Prisma.TiddlerEventUncheckedUpdateInput>
  /**
   * Choose, which TiddlerEvent to update.
   */
  where: Prisma.TiddlerEventWhereUniqueInput
}

/**
 * TiddlerEvent updateMany
 */
export type TiddlerEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TiddlerEvents.
   */
  data: Prisma.XOR<Prisma.TiddlerEventUpdateManyMutationInput, Prisma.TiddlerEventUncheckedUpdateManyInput>
  /**
   * Filter which TiddlerEvents to update
   */
  where?: Prisma.TiddlerEventWhereInput
  /**
   * Limit how many TiddlerEvents to update.
   */
  limit?: number
}

/**
 * TiddlerEvent updateManyAndReturn
 */
export type TiddlerEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * The data used to update TiddlerEvents.
   */
  data: Prisma.XOR<Prisma.TiddlerEventUpdateManyMutationInput, Prisma.TiddlerEventUncheckedUpdateManyInput>
  /**
   * Filter which TiddlerEvents to update
   */
  where?: Prisma.TiddlerEventWhereInput
  /**
   * Limit how many TiddlerEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TiddlerEvent upsert
 */
export type TiddlerEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * The filter to search for the TiddlerEvent to update in case it exists.
   */
  where: Prisma.TiddlerEventWhereUniqueInput
  /**
   * In case the TiddlerEvent found by the `where` argument doesn't exist, create a new TiddlerEvent with this data.
   */
  create: Prisma.XOR<Prisma.TiddlerEventCreateInput, Prisma.TiddlerEventUncheckedCreateInput>
  /**
   * In case the TiddlerEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TiddlerEventUpdateInput, Prisma.TiddlerEventUncheckedUpdateInput>
}

/**
 * TiddlerEvent delete
 */
export type TiddlerEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
  /**
   * Filter which TiddlerEvent to delete.
   */
  where: Prisma.TiddlerEventWhereUniqueInput
}

/**
 * TiddlerEvent deleteMany
 */
export type TiddlerEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TiddlerEvents to delete
   */
  where?: Prisma.TiddlerEventWhereInput
  /**
   * Limit how many TiddlerEvents to delete.
   */
  limit?: number
}

/**
 * TiddlerEvent without action
 */
export type TiddlerEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiddlerEvent
   */
  select?: Prisma.TiddlerEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiddlerEvent
   */
  omit?: Prisma.TiddlerEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiddlerEventInclude<ExtArgs> | null
}
