
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Bag: 'Bag',
  BagPermission: 'BagPermission',
  Tiddler: 'Tiddler',
  TiddlerEvent: 'TiddlerEvent',
  Template: 'Template',
  TemplatePermission: 'TemplatePermission',
  Recipe: 'Recipe',
  RecipePermission: 'RecipePermission',
  RecipeBag: 'RecipeBag',
  Settings: 'Settings',
  Roles: 'Roles',
  Users: 'Users',
  Sessions: 'Sessions'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created: 'created',
  updated: 'updated',
  description: 'description'
} as const

export type BagScalarFieldEnum = (typeof BagScalarFieldEnum)[keyof typeof BagScalarFieldEnum]


export const BagPermissionScalarFieldEnum = {
  bag_id: 'bag_id',
  role_id: 'role_id',
  level: 'level'
} as const

export type BagPermissionScalarFieldEnum = (typeof BagPermissionScalarFieldEnum)[keyof typeof BagPermissionScalarFieldEnum]


export const TiddlerScalarFieldEnum = {
  bag_id: 'bag_id',
  title: 'title',
  created: 'created',
  updated: 'updated',
  revision: 'revision',
  fields: 'fields'
} as const

export type TiddlerScalarFieldEnum = (typeof TiddlerScalarFieldEnum)[keyof typeof TiddlerScalarFieldEnum]


export const TiddlerEventScalarFieldEnum = {
  seq: 'seq',
  bag_id: 'bag_id',
  title: 'title',
  type: 'type'
} as const

export type TiddlerEventScalarFieldEnum = (typeof TiddlerEventScalarFieldEnum)[keyof typeof TiddlerEventScalarFieldEnum]


export const TemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  created: 'created',
  updated: 'updated',
  type: 'type',
  definition: 'definition'
} as const

export type TemplateScalarFieldEnum = (typeof TemplateScalarFieldEnum)[keyof typeof TemplateScalarFieldEnum]


export const TemplatePermissionScalarFieldEnum = {
  template_id: 'template_id',
  role_id: 'role_id',
  level: 'level'
} as const

export type TemplatePermissionScalarFieldEnum = (typeof TemplatePermissionScalarFieldEnum)[keyof typeof TemplatePermissionScalarFieldEnum]


export const RecipeScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  created: 'created',
  updated: 'updated',
  template_id: 'template_id',
  definition: 'definition',
  plugins: 'plugins',
  compiledAt: 'compiledAt'
} as const

export type RecipeScalarFieldEnum = (typeof RecipeScalarFieldEnum)[keyof typeof RecipeScalarFieldEnum]


export const RecipePermissionScalarFieldEnum = {
  recipe_id: 'recipe_id',
  role_id: 'role_id',
  level: 'level'
} as const

export type RecipePermissionScalarFieldEnum = (typeof RecipePermissionScalarFieldEnum)[keyof typeof RecipePermissionScalarFieldEnum]


export const RecipeBagScalarFieldEnum = {
  recipe_id: 'recipe_id',
  bag_id: 'bag_id',
  priority: 'priority',
  is_writable: 'is_writable',
  prefix: 'prefix'
} as const

export type RecipeBagScalarFieldEnum = (typeof RecipeBagScalarFieldEnum)[keyof typeof RecipeBagScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  key: 'key',
  value: 'value',
  updated: 'updated'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const RolesScalarFieldEnum = {
  role_id: 'role_id',
  role_name: 'role_name',
  description: 'description'
} as const

export type RolesScalarFieldEnum = (typeof RolesScalarFieldEnum)[keyof typeof RolesScalarFieldEnum]


export const UsersScalarFieldEnum = {
  user_id: 'user_id',
  username: 'username',
  email: 'email',
  password: 'password',
  created_at: 'created_at',
  last_login: 'last_login'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SessionsScalarFieldEnum = {
  session_id: 'session_id',
  created_at: 'created_at',
  last_accessed: 'last_accessed',
  session_key: 'session_key',
  user_id: 'user_id'
} as const

export type SessionsScalarFieldEnum = (typeof SessionsScalarFieldEnum)[keyof typeof SessionsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

